leeje0506/Persimmon-Algorithm-Study

- JIEUN/B2501.java
<a href="https://www.acmicpc.net/problem/2501" rel="nofollow">2501 약수 구하기</a>
> #4 
주어진 n 만큼 for문을 돌면서 0으로 나누어 떨어지는 수는 nums에 추가하고 정렬하여 k번째로 작은 수를 출력한다.
오류 메시지인 java.lang.ArithmeticException: / by zero는 자바 프로그램이 0으로 숫자를 나누려고 시도했을 때 발생한다. 정수 나눗셈에서 0으로 나누는 것은 수학적으로 정의되지 않으므로 런타임 예외를 발생시킨다. 
기초 문제 뽀개기를 하고 있는데 이런 문제일 수록 범위를 대충 보기 쉬워서 틀리는 경우가 많은 것 같다.
오늘도 이거 풀면서 0으로 나누기, n 포함 안 해서 나누기 같은 실수를 해서 틀렸습니다가 계속 떴다. 
주의가 많이 필요하다!
> jieun lee / 3월 4주차 / 3문제

- DONGHEON/[BOJ] 12497 통나무 건너뛰기
#4 
문제를 딱 보았을 때 생각나는 것은 통나무를 일단 정렬을 시켜야 겠다는 것이였다.
그냥 순차적으로 생각을 하면 너무 생각이 꼬여서 가장 높은 부분을 기준으로 생각을 했다.
10  20 25 가 존재 한다면 10 25 20 순으로 배열을 하는 것이 가장 차이가 많이 나는 곳의 수가 가장 적은 경우이다.
(앞의 경우 가장 차이가 많이 나는 곳인 10과 25의 차이가 15가 나고 뒤는 10과 20의 차이가 10이기 때문에)
이를 통해 오름차순으로 배열을 하고 한칸씩 띄엄 띄엄 계산을 하면 그게 정답이겠구나 싶었다.
풀이 방법이 딱 떠오르지 않으면 막막했을 것 같은 문제이다.
> dongheon choi / 3월 4주차 / 5문제

- JIEUN/B2309.java
<a href="https://www.acmicpc.net/problem/2309" rel="nofollow">2309 일곱 난쟁이</a>
> #18 
입력을 받아 전체 합을 만든 뒤, 두 난쟁이의 키를 뺐을 때 100이 되는 조합을 찾는다.
그리고 해당 난쟁이들을 제외하고 출력해주면 된다.
브루트 포스의 기초.
처음엔 스택에 넣은 후 pop 하는 과정으로 100을 만들려고 했다.
하지만 곧 브루트 포스 방식으로 돌아왔다.
> jieun lee / 3월 5주차 / 2문제

- JIEUN/B2693.java
<a href="https://www.acmicpc.net/problem/2693" rel="nofollow">2693 N번째 큰 수</a>
> #28 
난 단순하게 이중 for문으로 해봤다.
이 문제를 아주 어렵게 푸는 방법으로는 priorityQueue를 활용하는 방법이 있다.
[우선 순위 큐를 활용한 방법]
최대 힙 구조를 사용하여 배열의 원소들을 넣은 뒤, 3번째로 큰 원소를 찾기 위해 n-3번 원소를 제거하고, 남은 최대 힙의 루트 노드(가장 큰 원소)를 가져오면 되는 방식으로도 풀 수 있다. 
쉬운 문제를 풀면 잘만 하던 알고리즘을 갑자기 어..? 이거 어떻게 했더라 하고 혼란스러워진다는 것이다.
기초 재활을 하는 이유...
> jieun lee / 4월 1주차 / 1문제

- DONGHEON/[BOJ] 1931 회의실 배정
<a href="https://www.acmicpc.net/problem/1931" rel="nofollow">1931 회의실 배정</a>
#28
그리드 문제이다.
회의 시간이 일찍 끝나는 순으로 정렬해서 풀어주면 된다.
풀이에 그냥 일찍 끝나는 순으로 정렬해서 풀어주면 된다고는 했지만 생각보다 좀더 고려해야 할 점들이 있었다.
내가 놓치고 지나간 부분들도 꽤 존재해서 많이 실패했다.
> dongheon choi / 4월 1주차 / 5문제

- DONGHEON/[BOJ] 11053 가장 긴 증가하는 부분 수열
<a href="https://www.acmicpc.net/problem/11053" rel="nofollow">11503 가장 긴 증가하는 부분 수열</a>
#44 
DP 문제이다.
가장 긴 증가하는 부분 수열2 문제를 최근에 푼적이 있었다. 그 문제는 이분 탐색 문제로 지금 문제보다 더 큰 입력값들이 주어 져 있었다. 
같은 문제라도 다른 방법으로 풀어 보는 게 재밌다.  DP 방식은 풀어도 풀어도 안 익숙해 지는 건 승질난다.
이분 탐색도 그렇고 DP도 그렇고 얼른 손에 익어야하는데 ㅠㅠ
> dongheon choi / 4월 2주차 / 3문제

- JIEUN/B24479.java
<a href="https://www.acmicpc.net/problem/24479" rel="nofollow">24479 알고리즘 수업 - 깊이 우선 탐색 1 </a>
> #167 
/*
작성자 : 이지은
작성일시 : 2024-07-4, 목, 14:6
입력 : 정점의 수 n, 간선의 수 m, 시작 정점 r
다음 m개의 줄에 간선 정보 u v (가중치 1)
출력 : 노드의 방문 순서.
n개의 줄에 정수 출력. i번째 줄 = 정점 i의 방문 순서. 방문할 수 없는 경우 0.
조건 : 인접 정점은 오름차순으로 방문한다.
문제풀이 : 깊이 우선 탐색. 인접 리스트 사용.
*/
Boolean 과 boolean 의 차이.
Boolean 객체 배열은 기본적으로 null로 초기화되므로 NullPointerException이 발생할 수 있다. 반면에, boolean 기본 타입 배열은 false로 초기화된다.
인텔리제이 대소문자 구분 풀어뒀더니 Boolean으로 입력되서 널포인트 에러가 떴다. 덕분에 이런 내용도 알게 되네.
> jieun lee / 7월 1주차 / 2문제

- DONGHEON/[BOJ] 1052 물병
<a href="https://www.acmicpc.net/problem/1052" rel="nofollow">1052 물병</a>
#203 
수학 문제에 가까운 문제이다. 주어진 수에 가장 가까운 2의 제곱수를 찾고 빼주면서 필요한 물병의 수를 찾아가는 문제이다.
몇번 봤던 문제인데 도무지 문제 이해가 되지 않던 문제였다.
직접적으로 주어지지 않는 조건은 물병을 합칠때 같은 용량의 물이 담긴 물병끼리만 합칠 수 있다.(이 조건을 직접적으로 주지 않아서 나는 문제 자체가 잘못된 문제라고 생각했다.)
그 외에도 k개 이하인 경우도 가능 하기에 이 조건도 놓치면 틀릴 수 있는 문제이다.
간만에 머리를 좀 쓰는 느낌이다.
> dongheon choi / 8월 1주차 / 4문제

- DONGHEON/[BOJ] 1976 여행 가자
<a href="https://www.acmicpc.net/problem/1976" rel="nofollow">1976 여행가자</a>
#296 
bfs와 같은 그래프 탐색으로도 문제를 해결 할 수 있지만, 유니온 파인드를 사용하여 문제를 해결하였다.
유니온 파인드의 속도를 개선하기 위한 방법으로 find를 진행 하면서 노드를 갱신 하는 방법과 weight를 주는 방법이 존재한다.
예전에 풀었던 문제인데 예전에 풀었던 방법은 그래프 탐색으로 문제를 풀었었다. 이번에는 유니온 파인드를 공부하기 위해 유니온 파인드를 사용했다. 속도는 큰 차이는 없지 만 ms196 -> ms144로 개선이 되었다. 문제에서 좀 더 N이 커진다면 이 속도 차이는 좀 더 극명하게 날 것으로 보인다.
> dongheon choi / 9월 4주차 / 4문제

- DONGHEON/[BOJ] 1157 버블소트
<a href="https://www.acmicpc.net/problem/1517" rel="nofollow">1517 버블소트</a>
#304 
이름은 버블 소트이지만 실제로 버블소트를 사용해서 문제를 풀면 시간 복잡도가 O(n^2)이라 시간초과가 발생한다.
풀이 방법은 다양하지만 세그먼트 트리로 문제를 해결했다.
pair(value, idx)를 만들어 value기준 오름차순으로 sort해주고, 세그먼트 트리에 하나씩 update 시켜 가면서 result값을 찾았다.
작은 수가 먼저 세그먼트트리에서 해당 idx와 관련 있는 노드에 update가 되기 때문에 update를 진행 하면서 자신의 idx 이후의 값들을 sum 해주었다.
푸는 방법보다 이문제가 어찌 세그먼트 트리로 풀리는지 이해하는 것이 더 어려운 문제였다. 말로 설명되어 있는 것만으로는 이해하기가 힘들어 코드를 뜯어 보면서 이해를 했다.
> dongheon choi / 10월 1주차 / 3문제

- DONGHEON/[BOJ] 7578 공장
<a href="https://www.acmicpc.net/problem/7578" rel="nofollow">7578 공장</a>
#313 
어제 풀었던 방법과 동일하다. 다만 이번에는 입력값을 저장하는 방법에 차이가 존재한다. 나는 hashmap을 이용해서 값을 저장했는데 오히려 이게 속도를 느리게 하는거 아닌가 싶다.
이제는 다른 종류의 알고리즘도 공부를 해야겠다.
> dongheon choi / 10월 2주차 /3문제

- JIEUN/B11947.java
<a href="https://www.acmicpc.net/problem/11947" rel="nofollow">11947 이런 반전이</a>
> #319 
n : 양의 정수
F(n) : n의 각 자리 수 a에 대해서 그 수를 (9-a)로 바꾼 것
가장 큰 자리수의 유효숫자보다 앞에 등장하는 0들은 무시한다.
9의 반전은 0, 91의 반전은 8, 124의 반전은 875, 990의 반전은 9
사랑스러움 : n * F(n)
입력 : N
출력 : 1이상 N이하인 수들의 '사랑스러움' 중 최댓값
Banjeon() :  n의 반전을 구하는 메서드.
각 자리수 a 를 반전한 reverseNumber이 0이 아니라면 Zero를 true.
true인 경우 reversNumber에 10씩 곱해서 더해준다. (multiplier 시작 1)
Lovely() : n * Banjeon(n)의 최댓값을 구하는 메서드.
1이상 n이하를 돌면서 max 를 구한다. 
=> 사실 이 부분 때문에 시간초과, 메모리초과 난리 났음. 
이 문제는 풀기는 성공했지만, 통과를 하지는 못 했다.
이유는 시간 초과. 
n의 범위가 (1 ≤ N ≤ 1,000,000,000) 이기 때문에 배열로 저거 다 돌면 당연히 터진다.
배열을 고쳐서 해결이 될 수도 있는데, 뭔가 저 숫자의 규칙을 찾을 수 있다면 최적화 할 수 있을 거 같아서 고민을 하다가... 일단 제출하고 더 고민해보기로. 
+ 수정)
0 ~ 9 : 사랑스러움 최댓값은 5에서 나옴 (5 * 4 = 20)
10 ~ 99 : 사랑스러움 최댓값은 50에서 나옴 (50 * 49 = 2450)
그렇다면 …
> Jieun lee / 10월 4주차 / 2문제

- JIEUN/B2644.java
<a href="https://www.acmicpc.net/problem/2644" rel="nofollow">2644 촌수계산</a>
> #324 
조건 :
부모 자식 사이 1촌
입력 :
n  (전체 사람의 수)
a b (촌수를 계산해야하는 두사람)
m (부모 쟈식들 간의 관계 개수)
x y (부모자식 관계 m개, x:부모 y:자식)
출력 :
a b 의 촌수.
(친척 관계가 아니라면 -1)
부모와 자식, 자식과 부모를 갈 수 있어야 하기 때문에 양방향 그래프 사용한다
최단경로 찾기에 유리한 Bfs로 탐색.
bfs() : 연결된 노드들로 이동하면 거리 증가. 관계가 없다면 -1 반환.
> Jieun lee / 10월 5주차 / 3문제

- JIEUN/B2178_new
<a href="https://www.acmicpc.net/problem/2178" rel="nofollow">2178 미로 턈색</a>
> #338 
입력 :
첫 줄: N과 M (미로의 세로 크기 N, 가로 크기 M).
다음 N개의 줄: M개의 정수로 구성된 미로 배열. 1은 이동할 수 있는 칸, 0은 이동할 수 없는 칸.
출력 :
(1, 1)에서 (N, M)까지 도달하기 위해 지나야 하는 최소 칸 수.
조건 :
2 ≤ N, M ≤ 100
항상 도착 위치까지 이동할 수 있는 경우만 입력으로 주어짐.
BFS는 최단 경로를 찾기에 적합하므로, 큐를 사용하여 (1, 1)부터 BFS를 시작.
상하좌우 네 방향으로 이동하면서 이동할 수 있는 칸이 있으면 방문하고, 이전 칸의 거리 +1로 갱신.
BFS가 종료되면 (N, M) 위치에 저장된 최소 칸 수 출력.
> Jieun lee / 11월 1주차 / 2문제

- DONGHEON/[PGS] 250136 석유시추
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/250136#" rel="nofollow">250136 [PCCP 기출문제] 2번 석유 시추
</a>
#338 
일단 문제가 dfs로 풀면 에러가 터지게 되어 있어서 이걸 찾는데 오래 걸렸다. 이문제는 각 석유 풀마다 넘버링을 해서 저장을 해두어야 한다. 아니면 시간 초과가 발생한다. 
간만에 제대로 dfs bfs에 대해 제대로 복습한 느낌이다. 생각보다 신경써야 할 부분들이 많았고 이렇게 까지 해줘야해? 생각하면 해줘야 했다.
> dongheon choi / 11월 1주차 / 4문제

- DONGHEON/[PGS] 148652 유사 칸토어 비트열
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/148652" rel="nofollow">148652 유사 칸토어 비트열</a>
#346 
재귀를 이용하여 문제를 풀었다.
n 번째 비트열을 5등분 하여 1번째 2번째 4번째 5번째  파트는 n-1 번째 비트열과 동일하고 3번째 파트는 0이라는 것을 이용하여 문제를 해결했다. 
세그먼트 트리를 공부할 때 비슷하게 문제를 몇번 푼적이 있어서 그런지 푸는 방법 자체는 빠르게 떠올릴 수 있었는데 중간중간 조건들을 줘야할 것들이 많이 존재했다.
문제를 다풀고 다른 사람의 풀이를 보니 내가 푼 코드의 3분의 1정도의 코드들이 많았다. 그 방식은 5진법을 이용하여 문제를 푼 것들이다. 실행 시간은 내 코드가 빨랐다.
> dongheon choi / 11월 2주차 / 1문제

- DONGHEON/[PGS] 12987 숫자게임
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/12987" rel="nofollow">12987 숫자 게임</a>
#364 
이문제에서 중요한 점은 A의 순서가 큰 상관이 없다는 점이다. 따라서 A를 sort 시켜도 상관이 없다. A를 오름차순으로 정렬시켜둔 후에 B를 priorityqueue 에 넣어둔다 . 그 후 우선 순위 큐에서 하나씩 poll 해가면서 A의 원소보다 높을때만 idx를 옮겨주면서 체크해 나가면 된다.
오히려 LEVEL 2의 문제보다도 쉬운 문제였다.
> dongheon choi /11월 4주차 / 2문제

- DONGHEON/[BOJ] 11559 뿌요뿌요
<a href="https://www.acmicpc.net/problem/11559" rel="nofollow">11559 뿌요뿌요</a>
#405
bfs를 사용한 시뮬레이션 문제이다. 한번의 행동이 끝날때마다 bfs를 돌려 터지는 부분들을 측정하고 해당 부위의 윗부분에 해당하는 아이들을 내려주면 되는 문제이다.
> dongheonchoi / [시뮬레이션] / 뿌요뿌요 / 골드 4

- DONGHEON/[BOJ] 314 이중우선순위큐
<a href="https://www.acmicpc.net/problem/314" rel="nofollow">314 이중우선순위큐</a>
#405
그냥 우선순위큐 두개를 가지고 풀었더니 시간초과가 자꾸 발생하여 찾아봤더니  remove함수가 O(N)의 시간이 걸리는 것이 문제 였다. 이를 map을 사용하여 시간을 줄여주는 것이 포인트였다.
구글링하여 문제를 푼것이라 제대로 이해를 한것이 맞는지 잘 모르겠어서 다시한번 풀어보면서 생각을 해봐야겠다
treeMap을 이용하면 최소값 최대값을 바로 잡아낼 수 있어서 우선순위 큐를 사용하지 않고도 문제 해결이 가능했다.
treeMap에 대해 공부도 한번 해봐야겠다
> dongheonchoi / [힙] / 이중우선순위큐 / 골드 4

- DONGHEON/[BOJ] 2636 치즈
<a href="https://www.acmicpc.net/problem/2636" rel="nofollow">2636 치즈</a>
#439 
그래프 탐색 문제이다.
최대한 풀이 시간을 줄여보기 위해서 한번 공기에  접촉 되었던 부분은 다시는 방문하지 않도록 코드를 작성했다.
치즈였던 부분이 공기와 접촉하는 경우 해당 치즈 부분을 담아뒀다가 한번의 사이클이 다 돌 때 처리를 해주었다.
DFS, BFS  너 마저
> dongheonchoi / [그래프] 치즈 / 골드 4
