leeje0506/Persimmon-Algorithm-Study

- DONGHEON/[BOJ] 14503 로봇 청소기
> #5
시뮬레이션 문제
예전에 애들이 푸는거 도와 줬던 적이 있엇는데 내가 풀려니까 잘 안풀린다 ㅠㅠ
> dongheon choi /  3월 4주차 / 2문제

- JIEUN/B1012
<a href="https://www.acmicpc.net/problem/1012" rel="nofollow">1012 유기농 배추</a>
> #4 
델타를 사용해 상하좌우 인접한 배추를 세어서 필요한 지렁이의 수를 구하면 된다. 
DFS
유기농 배추는 달팽이 이후로 내가 델타를 쓰는 것에 자신감을 붙여줬던 문제 중 하나다. 
다시 푸니까 반갑다. 언제쯤 그래프 탐색과 이 지겨운 싸우고 화해하고를 그만 반복할 수 있을까.
> jieun lee / 3월 4주차 / 2문제

- DONGHEON/[BOJ] 1202 보석 도둑
#4
자료 구조 문제이다 처음에는 해쉬 맵을 써서 풀까 했으나 그 경우 가방의 무게를 고려하기가 힘들어서 그냥 class 를 만들어서 문제를 풀어주었다,
같은 문제를 1학기때 풀었던 거 기억이 있다. 그때는 좀 더 수월하게 풀었던거 같은데
> dongheon choi / 3월 4주차 / 3문제

- minjeong/[BJ] 11659 구간 합 구하기 4
<a href="https://www.acmicpc.net/problem/11659" rel="nofollow">11659 구간 합 구하기 4</a>
누적합으로 풀이하는 문제라고 했는데,  자꾸 시간초과가 났다...
누적합으로 풀이를 할 때에는 연산 횟수를 줄이는 것이 중요한 것 같다 .
누적합인 배열을 하나 만들어서 구간 별로 뺄셈을 이용하여 풀이하니 통과할 수 있었다.
--
어제 푼 문제랑 오늘 푼 문제는 모두 내가 두세달 전에 시간 초과 이슈로 실패했던 문제들이다.
지금 생각해보니 알고리즘을 곁들인 수학적 사고력이 어느정도 필요했던 것 같다. 이런 문제를 좀 더 자주 접해봐야지.
> Create [BJ] 11659 구간 합 구하기 4

- DONGHEON/[BOJ] 17503 맥주 축제
#4
그리드 문제이다.
class를 생성해서 도수 별로 정렬한 것을 더해주다가 빼줄 때는 선호도를 기준으로 빼주면 된다.
생각보다 그리드가 막하면 되는 문제가 아니고 신경 쓸 부분이 많다.
처음에 제출 했을 때 틀렸는데 문제가 선호도를 다 채우더라도 맥주 마신 갯수가 맞지 않으면 틀렸었다.
걸린시간 888이라 사진 찍어봄 ㅎㅎ
> dongheon choi / 3월 4주차 / 4문제

- minjeong/[BJ] 11286 절댓값 힙
<a href="https://www.acmicpc.net/problem/11286" rel="nofollow">11286 절댓값 힙</a>
우선순위 큐는 최소힙이기 때문에 이걸로 문제를 풀면 된다고 생각했다.
그런데 "절대값이 가장 작은 수" 를 찾아야 하기 때문에 추가적인 비교 연산이 필요했다.
고민하다가 인터넷을 찾아봤는데, 우선순위 큐에 새로운 비교 연산을 설정하는 방법을 알게 됨!
우선순위 큐에 비교 연산 추가하기
```
PriorityQueue<Integer> pq = new PriorityQueue<>(new Comparator<Integer>() {
@Override
public int compare(Integer a, Integer b) {
int A = Math.abs(a);
int B = Math.abs(b);
if (A > B)
return A - B;
else if (A == B) {
if (a > b)
return 1;
else
return -1;
} else
return -1;
}
});
```
요즘 개념을 챙기면서 살짝 응용된 문제를 풀어보면서, 이렇게도 풀 수가 있구나~ 하고 신기하는 중이다...
> minjeong / 3월 4주차 / 3문제

- minjeong/[BJ] 12789 도키도키 간식드리미
<a href="https://www.acmicpc.net/problem/12789" rel="nofollow">12789 도키도키 간식드리미</a>
스택과 큐의 개념을 활용하여 간단히 풀 수 있는 문제이다.
그런데 간단히 못 풀고 4번 틀렸습니다. 봤다 이유는 while 문에서 return 을 안 쓰고 break 를 썼기 때문에... while 에서의 return 과 break 의 차이를 다시 한 번 알아보고 정리하는 게 좋을 것 같다. 
쉬운 문제라고 방심하지 말아야한다. 어디서 틀릴지 모른다.
> minjeong / 3월 4주차 / 4문제

- JIEUN/B2460.java
- JIEUN/B3460.java
<a href="https://www.acmicpc.net/problem/3460" rel="nofollow">3460 이진수</a>
> #4 
직접 나누는 방법을 쓰다가 2진수 변환이 가능한 Integer.toBinaryString()을 사용했다.
Java 10진수 -> 2진수 변환
Integer.toBinaryString(int i)
반환타입은 String
%, /
정수를 2로 나누었을 때 나머지가 1이면 이진수로 나타냈을 때 1이고, 0이면 이진수로 나타냈을 때 0인 점을 사용해서 변환값을 구할 수 있다. 몫이 0이 될 때까지 반복하면 된다.
이진수!
> jieun lee / 3월 4주차 / 4문제

- JIEUN/B10870.java
<a href="https://www.acmicpc.net/problem/10870" rel="nofollow">10870 피보나치 수 5</a>
> ex) #18 
피보나치 수는 재귀의 기본 중 기본이다.
Fn = Fn-1 + Fn-2 
이걸 '피보나치' 라는 메서드로 만들어서 원하는 값일 때까지 재귀 안의 재귀 안의 재귀.. 이런 식으로 돌게 만들면 된다. 
수학적인 머리가 비상하지 못해서 재귀를 할 때마다 안에서 이루어지는 로직까지 생각하기가 어렵다.
피보나치는 그 중에서도 제일 간단한 재귀의 바이블인데 풀면서도 생각하면 머리가 꼬여버린다.
일단 틀을 외우고 내용을 억지로 이해하는 식으로 해서 그런지 응용이 잘 되지 않는 것이 힘들다. 
이 코드를 이해하기에 알맞은 이미지가 있어서 찾아와봤다.
> jieun lee / 3월 5주차 / 1문제

- DONGHEON/[BOJ] 2343 기타 레슨
#18 
이분 탐색 문제이다, 이분 탐색을 돌면서 비디오 테이프가 몇개가 나오는지를 계산하고 그에 맞게 이분탐색을 한다.
이분 탐색 문제는 진짜 모르겠다. 아직도 감이 안잡힌다. 계속 낮은 단계 문제들  풀면서 이해부터 제대로 해야될것 같다.
내가 이해가 안되는 부분 어떨땐  hi = mid -1; 을 할 때가 있고 어떨 땐 hi = mid; 를 해도 될 때가 있는데 이 두 경우의 차이를 모르겠다.
> dongheon choi / 3월 5주차 / 1문제

- DONGHEON/[BOJ] 1946 신입사원
#18 
그리드 문제이다. 이중 포문을 사용하면 안되는 문제이다. 
최근에 계속 class 를 만들어 쓰는 버릇을 들였더니 그냥 배열을 만들어서 하는 게 익숙하지가 않네...
간만에 1학기에 풀던 문제들 느낌을 받았다.
재미있는 문제 였다. 퀴즈 푸는 것 같은 문제이다.
> dongheon choi / 3월 5주차 / 2문제

- minjeong/[PG] 147355 크기가 작은 부분 문자열
- minjeong/[PG] 82612 부족한 금액 계산하기
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/82612" rel="nofollow">82612 부족한 금액 계산하기</a>
```
class Solution {
public long solution(int price, int money, int count) {
long answer = 0;
long tmp = 1;
while(count-- >0){
money -= price*tmp;
tmp++;
}
if(money < 0)
answer = Math.abs(money);
return answer;
}
}
```
자신있게 제출 했는데 테스트 케이스 23개 중 4개가 틀렸다!
왜 틀렸나 생각해보니까 money 는 int 로 들어오기 때문에 값이 벗어났을 때 처리를 못하는 것 같았다.
long 으로 total 을 선언하여 다시 작성해주니 잘 돌아감!
이런 기초 알고리즘을 풀 때마다 자신만만하게 틀린다...
좀 더 컴퓨터처럼 생각할 수 있게 노력해야겠다.
> minjeong / 3월 5주차 / 3문제

- minjeong/[PG] 147355 크기가 작은 부분 문자열
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/147355" rel="nofollow">147355 크기가 작은 부분 문자열</a>
어제 문제 머지 안 돼 있어서 오늘 푼 문제가 어제 올린 풀리퀘에 합쳐짐...
```
import java.util.*;
class Solution {
public int solution(String t, String p) {
int answer = 0;
long num = 0;
for(int i = 0; i < t.length()-p.length()+1; i++){
num = Long.parseLong(t.substring(i, i + p.length()));
if(num <= Long.parseLong(p)) answer++;
}
return answer;
}
}
```
p의 길이에 주의하며 풀어야 한다. p의 길이는 최대 18글자이므로, int 의 범위를 벗어난다.
이것 때문에 런타임 에러가 계속 뜸!
> minjeong / 3월 5주차 / 4문제

- JIEUN/B2609.java
<a href="https://www.acmicpc.net/problem/2609" rel="nofollow">2609 최대공약수와 최소공배수</a>
> #18 
최대공약수, 최소공배수를 구하면 되는 간단한 알고리즘 문제다.
처음에는 브루트 포스적으로 풀어보려고 했으나, 비효율적으로 변수가 늘어나는 것 같아 유클리드 호제법을 이용했다.
```
//일반적인 약수 구하기 알고리즘
int n = 100;
for(int i = 1; i <= n; i++){
if(n % i == 0){
System.out.println(i + "는 약수 입니다.");
}
}
```
기초를 탄탄하게  공부하자.
> jieun lee / 3월 5주차 / 3문제

- DONGHEON/[ETC] 6268 전광판
#18 
다른 방법이 존재 하는지 모르겠다. 이런 식으로 풀기 싫엇는데 그냥 전부 다 만들어서 풀어버렸다.
누군가 이 문제를 본다면 다른 방법으로 풀수 있는지 확인 해주면 좋겠다.
문제 자체는 어렵지 않아서 한번 봐주면 좋겟다
> dongheon choi / 3월 5주차 / 3문제

- DONGHEON/[ETC] 6270 GBC
- DONGHEON/[ETC] 7726 나무섭지
#28 
자료구조를 이용하여 이중 while문을 통하여 풀었다.
1학기 때 분명 어디선가 보던 문제인데 무슨 문제인지는 기억 안난다. 
지금 푸는 방식과 다르게 풀었을것 같다.  그 당시에는 que 도 모르고 class 를 만들어 하는 법도 몰랐으니 배열을 만들어서 풀지 않았을까 싶다.
> dongheon choi / 4월 1주차 / 1문제

- DONGHEON/[BOJ] 4485 녹색 옷 입은 애가 젤다지?
<a href="https://www.acmicpc.net/problem/4485" rel="nofollow">4485 녹색 옷 입은 애가 젤다지?</a>
#28 
DFS로 풀다가 펑~! BFS로 푼다고 달라질것 같지 않았던 찰나에 pq가 떠올랐다. 그래프 탐색에서 pq 써서 하는건 엄청 오랫만인거 같았다.
그 뭐지 전쟁터에서 길 잇는 문제랑 비슷하다.
문제 이름 부터 킹받는 문제  그래서 젤다가 녹색 옷 입은 애가 맞지??? 그래서 젤다의 전설인거지??
> dongheon choi / 4월 1주차 / 3문제

- JIEUN/B1159.java
<a href="https://www.acmicpc.net/problem/1159" rel="nofollow">1159 농구 경기</a>
> #28 
해쉬맵을 사용했어요.
> jieun lee / 4월 1주차 / 3문제

- DONGHEON/[BOJ] 1309 동물원
- DONGHEON/[BOJ] 1931 회의실 배정
<a href="https://www.acmicpc.net/problem/1309" rel="nofollow">1309 동물원</a>
#28 
dp 문제이다
N퀸 처럼 백트래킹 식으로 풀려다가 뭔가 이상해서 보니 DP 문제였다 ㅠㅠㅠ
> dongheon choi / 4월 1주차 / 4문제

- minjeong/[PG] 120843 공 던지기/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120843" rel="nofollow">120843 공 던지기</a>
```
idx = idx % numbers.length;
```
처음에는 원형 큐를 써야 하는 문제인 줄 알았는데, 다시 생각해보니까 모듈러 연산으로도 할 수 있을 것 같았다.
idx 를 numbers 배열의 길이로 나눈 나머지가 결국엔 다시 idx 와 같다는 것을 이해하면 쉽게 풀 수 있다.
추가적으로 idx 는 바로 다음 사람은 한 번 건너 뛰어야 하므로 +2씩 증가한다.
[여기를 클릭하면 모듈러 연산에 대해 알 수 있음](https://ko.khanacademy.org/computing/computer-science/cryptography/modarithmetic/a/what-is-modular-arithmetic)
SQL 하다가 JAVA 하니까 좋다...
> minjeong / 4월 1주차 / 4문제

- DONGHEON/[BOJ] 1072 게임
<a href="https://www.acmicpc.net/problem/1072" rel="nofollow">1072 게임</a>
#44 
기본적인 이분 탐색 문제이다.
이분 탐색을 공부하려고 보다 보니까 풀이 실패 문제가 있어서 다시 풀어봤다.
어찌 풀었는지 확인하니 아주 알고리즘 베이비 처럼 풀어 두었다.
1씩 키워주면서 맞는게 나올 때까지 반복하기...
> dongheon choi / 4월 2주차 / 1문제

- JIEUN/B2563.java
- jieun/B2563.java
<a href="https://www.acmicpc.net/problem/2563" rel="nofollow"2563 색종이</a>
#44 
오랜만에 스캐너 쓰고 렉 걸림
> Jieun lee / 4월 2주차 / 1문제

- DONGHEON/[BOJ] 1300 K번째 수
<a href="https://www.acmicpc.net/problem/1300" rel="nofollow">1300  K번째 수</a>
#44 
그냥 2탐색 문제인데 어디서 써야 될지가 많이 어렵다.
수학적인 번뜩임이 있어야 할듯 하다.
난 없어서 찾아 봤다.
문제 자체는 짧은데 찾는 부분이 어렵다
> dongheon choi / 4월 2째주 / 2문제

- DONGHEON/[BOJ] 14500 테트로미노
<a href="https://www.acmicpc.net/problem/14500" rel="nofollow">14500 테트로미노</a>
#44
1학기때 자주 풀었던 유형의 문제이다.  2번째에 그냥 한번 더 탐색을 들어가면 해결되는 문제이다.
제일 처음 A형 문제와 매우 유사하다. 이 문제를 이제야 풀어본다.
사실 빛코마 문제로 나왔던 문제인데 그때 시간초과 당하고 다시 안 풀어 봤었다.
> dongheon choi / 4월 2주차 / 4문제

- DONGHEON/[BOJ] 2812 크게 만들기
<a href="https://www.acmicpc.net/problem/2812" rel="nofollow">2812 크게 만들기 </a>
#55 
옛날에 풀었던 스택 문제와 유사하다.
그리드 문제를 풀어보려고 했는데 사실은 스택 문제였다. 정말 얼마만에 스택을 사용해보는지 모르겠다.
게시판에서 반례를 주지 않았으면 훨씬 많은 시간이 걸렸을 것 같다.
> dongheon choi / 4월 3주차 / 1문제

- DONGHEON/[BOJ] 2589 보물섬
<a href="https://www.acmicpc.net/problem/2589" rel="nofollow">2589 보물섬</a>
#55 
BFS로 푸는 문제이다.
최단거리를 구하는 알고리즘을 사용하려 했으나 그 알고리즘은 MST에서만 가능 하다고 한다.
그래프에 루프가 존재하면 안된다고 함,,,
나와 같은 생각으로 문제를 풀려던 사람이 있어서 나도 잘못 되었다는 것을 깨달았다.
현재 풀이 실패를 하여 다시 도전을 해야겠다.
<a href="https://www.acmicpc.net/board/view/66007" rel="nofollow">도움받은 게시글</a>
> dongheon choi / 4월 3주차 / 3문제

- JIEUN/P59046.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/59046" rel="nofollow">59046 루시와 엘라 찾기</a>
> #55 
이름이 Lucy, Ella, Pickle, Rogan, Sabrina, Mitty 중 하나인 동물들의 정보가 ANIMAL_ID에 따라 정렬되어 출력
> jieun lee / 4월 3주차 / 2문제

- DONGHEON/[BOJ] 13549 숨바꼭질3
<a href="https://www.acmicpc.net/problem/13549" rel="nofollow">13549 숨바꼭질 3</a>
#55  
pq로 문제를 해결했다.
true를 먼저 처리하냐 나중에 처리하냐에 따라 틀리고 맞고가 갈렸다.
나중에 처리하는게 맞는 방법이었다.
> dongheon choi / 4월 3주차 / 4문제

- DONGHEON/[BOJ] 13913 숨바꼭질4
<a href="https://www.acmicpc.net/problem/13913" rel="nofollow">13913 숨바꼭질4</a>
#55
이전에 풀었던 숨바꼭질3과 크게 변한 부분은 없다. 단지 이동하는 과정을 다 저장을 해야하는데 이부분에서 풀이시간을 많이 잡아먹어서 2300ms가 나온다.
StringBuilder로 저장하고 풀면 시간을 줄일수 있을까 싶은데 StringBuilder를 들고 다니면서 계산을 한적이 없어서 어찌 활용해야 하는지 잘 모르겠다. 이부분도 공부 해봐야겠다.
> dongheon choi / 4월 3주차 / 5문제

- minjeong/[PG] 59406 동물 수 구하기 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/59406" rel="nofollow">59406 동물 수 구하기</a>
SELECT COUNT(*) as count
FROM ANIMAL_INS
```
SELECT COUNT(*) FROM 테이블;
```
```
SELECT COUNT(컬럼) FROM 테이블;
```
> minjeong / 4월 3주차 / 4문제

- DONGHEON/[BOJ]  9935 문자열폭발
<a href="https://www.acmicpc.net/problem/9935" rel="nofollow">9935 문자열 폭발</a>
#70 
stack을 사용하여 문제를 풀었다.
StringBuilder의 insert를 사용하여 문제를 풀었더니 시간초과가 계속 발생 했다. stack에서 뽑은 값을 역순으로 stringbuilder에 append 하고 싶으면 for(int a : stack ) 이 형식을 stack 에다가 사용하면된다.
그냥 아무 문제나 풀었는데 신기하게 팜플렛에 예시로 있는 문제 였다 신기하다 다 풀고 description 작성할때까지 몰랐다.
> dongheon choi / 4월 4주차 / 1문제

- DONGHEON/[BOJ] 1043 거짓말
<a href="https://www.acmicpc.net/problem/1043" rel="nofollow">1043 거짓말</a>
#70 
해쉬맵을 쓸까 하다가 사람의 수가 1,2,3,4와 같이 주어 지길래 그냥 ArrayList<ArrayList<Integer>> 두개를 써서 문제를 해결했다.
너무 지저분하게 푼 느낌이 있었는데 풀이 시간을 보니 잘못된 방향은 아닐 수도 있겠다. 그냥 입력 값의 크기가 작아서 풀이 시간이 적게 나온 거일 수도 있긴 하다.
> dongheon choi / 4월 4주차 / 2문제

- DONGHEON/[BOJ] 2212 센서
<a href="https://www.acmicpc.net/problem/2212" rel="nofollow">2212 센서</a>
#70 
그리드 방식으로 정렬을 총 3번을 시켜서 문제를 해결했다. 
comprable을 상속 받기도 하고 람다식도 쓰고 정렬하는 방법을 공부하기에 좋아보인다.
> dongheon choi / 4월 4주차 / 4문제

- DONGHEON/[BOJ] 1697  숨바꼭질
<a href="https://www.acmicpc.net/problem/1697" rel="nofollow">1697 숨바꼭질</a>
#70
일전의 풀었던 숨바꼭질 문제의 가장 기본 형이다.
숨바꼭질 1,2,3,4 마스터
> dongheon choi / 4월 4주차 / 5문제

- DONGHEON/[BOJ] 1092 배
<a href="https://www.acmicpc.net/problem/1092" rel="nofollow">1092 배</a>
#81 
그리드 방식으로 비교해준다
생각이 꼬여서 시간이 오래 걸렸다.
queue를 두개를 사용해서 진행을 하려했는데 그런식으로 하면 확인이 불가능한 부분이 생겨 버려 풀수가 없었다.
> dongheon choi / 5월 1주차 / 1문제 

- minjeong/[PG] 59046 루시와 엘라 찾기/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/59046" rel="nofollow">59046 루시와 엘라 찾기</a>
```
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN('Lucy','Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty') 
ORDER BY ANIMAL_ID
```
NAME 칼럼에 속한 것이 있나 체크 하는 방법으로 풀기...
근데 다른 방법으로 할 수 있나?
SQL 문법을 너무 모른다... 기본적으로 DB 를 하드하게 다뤄보면 좋을 것 같은데
> minjeong / 5월 1주차 / 1문제

- DONGHEON/[BOJ] 4811 알약
<a href="https://www.acmicpc.net/problem/4811" rel="nofollow">4811 알약</a>
#81
DP 방식이다.  점화식 푸는 대로 문제를 풀어주면 된다. 
이런 DP 방식은 진짜 코테에서는 안나올것같다.
점화식도 가물가물해서 기억도 안나는데 이런 문제 푸려니 고역이다.
> dongheon choi / 5월 1주차 / 2문제

- DONGHEON/[BOJ] 1283 소트
<a href="https://www.acmicpc.net/problem/9935" rel="1083">1083 소트</a>
#81 
가장 큰 수부터 시작해서 맨앞으로 이동시킬수 있는지 비교하면서 해결하면 되는 문제이다.
DFS , BFS , 그리디 같은 문제들만 풀다가 이런 문제들을 풀려니까 어찌 푸는지 감도 잘 안잡히고 어렵다.
> dongheon choi / 5월 1주차 / 3문제

- JIEUN/P17678.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/17678?language=java" rel="nofollow">17678 셔틀버스</a>
#81 
시간 형식의 문자열을 분으로 변환하는 함수를 만든다.
버스 시간표를 만든다.
크루들의 도착 시간을 정렬한다.
각 버스에 대해 크루들을 태우고, 콘이 탈 수 있는 가장 늦은 시간을 찾는다.
> jieun lee / 5월 1주차 / 1문제

- DONGHEON/[BOJ] 7562 나이트의 이동
<a href="https://www.acmicpc.net/problem/7562" rel="nofollow">7562 나이트의 이동</a>
#81
그래프 탐색에서 BFS 문제이다.
DFS가 편해서 DFS로 풀려다가 시간을 날려먹고 BFS로 문제를 풀었다.
DFS로 하려고 할경우 visited를 판단할때 문제가 발생한다.
한 좌표에 최소한의 움직임으로 간다는 보장이 없어서 풀 수가 없다
> dongheon choi / 5월 1주차 / 4문제

- DONGHEON/[BOJ] 1149 RGB거리
<a href="https://www.acmicpc.net/problem/1149" rel="nofollow">1149 RGB 거리</a>
#81 
간단한 DP 문제이다. 우주선 연료와 비슷한 문제
> dongheon choi / 5월 1주차 / 5문제

- DONGHEON/[BOJ] 1629 곱셈
<a href="https://www.acmicpc.net/problem/1629" rel="nofollow">1629 곱셈</a>
#90 
저번에 풀엇던 매트릭스곱을 구하는 방식과 유사하게 풀었다.
곱해주는 수를 증가시키면서 진행을 하였다.
아직도 long을 쓸때랑 int 쓸때를 자꾸 헷갈린다. 주어진 값이 int 범위라고 그냥 int 전부 썻다가 계산 되는 순간 펑~ ㅠㅠㅠㅠ
> dongheon choi / 5월 2주차 / 1문제

- DONGHEON/[BOJ] 1932 정수 삼각형
<a href="https://www.acmicpc.net/problem/1932" rel="nofollow">1932 정수 삼각형</a>
#90 
간단한 dp 문제이다. 위에서 부터 dp 배열과 mat 배열을 두고 dp를 계산해가면서 진행을 하면 된다. 아래에서 시작하면 시간을 좀더 줄일수 있을 것 같다.
실버 문제들이 골드 보다 세세한 조건이 더 까다로운 경우가 많아서 나 처럼 덤벙거리는 성격은 조건을 못찾고 고생을 많이 하는거 같다.
> dongheon choi / 5월 2주차 / 2문제

- minjeong/[BJ] 1181 단어 정렬/src
<a href="https://www.acmicpc.net/problem/1181" rel="nofollow">1181 단어 정렬</a>
1. Scanner 사용
2. 모든 원소 배열에 넣어 정렬하기
3. 정렬할 때 Comparator 사용하기
Comparator 는 정렬을 하기 위한 인터페이스로 Arrays.sort( ) 에는 내부적으로 구현이 되어있다!
``` java
// 내림차순 정렬을 위한 comparator 사용
Arrays.sort(arr, new Comparator<Integer>() {
public int compare(Integer i, Integer j) {
return j - i; 
}
});
```
**return j - i;** 구문에서, 두 정수 i1과 i2의 차이를 반환하는데, 이 반환 값에 따라 정렬이 결정된다.
양수를 반환하면 i 가 j 보다 "작다"고 간주되어 i 를 j 뒤로 정렬하고,
음수를 반환하면 i 가 j 보다 "크다"고 간주되어 i 를 j 앞으로 정렬하고,
0을 반환하면 i 와 j 가 같다고 간주되어 정렬 순서에 영향을 주지 않는다.
다음에는 comprable 에 대해서도 정리해봐야겠다.
> minjeong / 5월 2주차 / 2문제

- JIEUN/B10810.java
<a href="https://www.acmicpc.net/problem/10810" rel="nofollow">10810 공 넣기</a>
> #90 
1차원 배열에 공을 넣으면 된다
1차원 배열 다시 보니까 반갑다
1학기 때 민정이었나... 누가 공 넣기에 열심히던 것이 생각난다
> jieun lee / 5월 2주차 / 1문제

- JIEUN/B3085.java
<a href="https://www.acmicpc.net/problem/3085" rel="nofollow">3085 사탕 게임</a>
> #90 
민정이가 사준 사탕 또 사러 잠실 가고 싶다
> jieun lee / 5월 2주차 / 2문제

- DONGHEON/[BOJ] 2156 포도주 시식
<a href="https://www.acmicpc.net/problem/2156" rel="nofollow">2156 포도주 시식</a>
#90
연속된 3수를 선택 하면 안되는 문제 이다. 이 문제 역시 DP 문제 였는데 DP 문제 답게 이해를 했는데 이해한 기분이 들지 않는 문제이다. 
DP 문제는 너무 어렵다 봐도봐도 이해가 잘안된다 ㅠㅠ
> dongheon choi / 5월 2주차 / 4문제

- DONGHEON/[BOJ] 11403 경로 찾기
<a href="https://www.acmicpc.net/problem/11403" rel="nofollow">11403 경로 찾기</a>
#90 
그냥 그래프 탐색으로 풀면 될 것 같았는데 그러면 최악의 경우 1억번을 탐색해야 할것 같았다.
플로이드 와샬방식으로 탐색을 하면 문제를 해결 할 수 있었다.
> dongheon choi / 5월 2주차 / 5문제

- JIEUN/B5597.java
<a href="https://www.acmicpc.net/problem/5597" rel="nofollow">5597 과제 안 내신 분..? </a>
> #90 
과제를 미리미리 해야지~
누가 과제 안 하냐 ㅋㅋ 
안녕하세요 누 입니다.
> jieun lee / 5월 2주차 / 3문제

- JIEUN/B2231.java
<a href="https://www.acmicpc.net/problem/2231" rel="nofollow">2231 분해합</a>
> #90 
모든 경우를 시도하여 N의 생성자를 구하면 된다.
분해! 합!
> jieun lee / 5월 2주차 / 4문제

- minjeong/[BJ] 11279 최대 힙/src
<a href="https://www.acmicpc.net/problem/11279" rel="nofollow">11279  최대힙</a>
최소힙은 우선순위 큐이다. 최대힙을 만들 때엔 우선순위 큐를 사용하여 음수 부호를 붙여 넣고, 다시 음수 부호를 붙여 꺼내어 주면 된다.
easy 한 문제.
> minjeong / 5월 2주차 / 4문제

- DONGHEON/[BOJ] 11057 오르막 수
<a href="https://www.acmicpc.net/problem/11057" rel="nofollow">11057 오르막 수</a>
#️⃣연관된 이슈
#105 
DP로 문제를 해결했다.
재활을 하면서 이제는 슬슬 난이도를 올려야겠다
> dongheon choi / 5월 4주차 / 2문제

- minjeong/[PG]/181916 주사위 게임 3/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/181916" rel="nofollow">181916 주사위 게임 3</a>
정렬을 이용해서 삼항 연산 조건식으로 return 을 달아줬다.
변수를 할당해서 더 보기 좋게 만들 수도 있었을 것 같다.
오랜만에 알고리즘...
> minjeong / 5월 4주차 / 2문제

- minjeong/[PG]/181858 무작위로 K개의 수 뽑기/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/181858" rel="nofollow">181858 무작위로 K개의 수 뽑기</a>
K 만큼의 길이를 가진 배열을 미리 생성하고 -1로 초기화.
그리고 값이 포함됐는지 여부에 따라 추가하거나, 건너뛰거나!
```
import java.util.*;
class Solution {
public int[] solution(int[] arr, int k) {
int[] answer = new int[k];
for(int i = 0; i < k; i++){
answer[i] = -1;
}
for(int i = 0, j = 0; i < arr.length; i++){
if(j == k) break;
if(Arrays.asList(answer).contains(arr[i])){
continue;
} else {
answer[j] = arr[i];
j++;
}
}
return answer;
}
}
```
asList.contains 가 잘 되지 않고 있었던 것 같다...!
오랜만에 알고리즘 푸니까 꽤 재밌네..?
> minjeong / 5월 4주차 / 3문제

- JIEUN/B10448.java
<a href="https://www.acmicpc.net/problem/10448" rel="nofollow">10448 유레카 이론</a>
> #105
> jieun lee / 5월 4주차 / 1문제

- DONGHEON/[BOJ] 9465 스티커
<a href="https://www.acmicpc.net/problem/9465" rel="nofollow">9465 스티커 </a>
#105 
DP 문제 이다.
이젠 진짜 재활 한다....
> dongheon choi / 5월 4주차 / 3문제

- JIEUN/B1388.java
<a href="https://www.acmicpc.net/problem/1388" rel="nofollow">1388 바닥 장식</a>
> #105
> jieun lee / 5월 4주차 / 2문제

- DONGHEON/[BOJ] 2583 영역 구하기
<a href="https://www.acmicpc.net/problem/2583" rel="nofollow">2583 영역 구하기</a>
#105 
DFS 문제다 간만에 다시 DFS를 써보는거 같다
하나 하나 다시 재활하는 재미가 있는거 같다
> dongheon choi/ 5월 4주차 / 4문제

- JIEUN/B10989.java
- JIEUN/B1920.java
<a href="https://www.acmicpc.net/problem/1920" rel="nofollow">1920 수 맞추기</a>
> #116 
for문 2개를 돌리는 방식으로 풀었는데, N * M이라 그런지 시간초과에 딱 걸렸다.
입력을 다시 보니 최대 100,000 * 100,000이라 넘을 수 밖에 없었다.
버퍼드리더, 스트링빌더를 이미 사용 중이기 때문에 로직을 바꿔야 한다고 생각했다.
탐색 방법 중 이진탐색을 이용하기로 했다.
이진탐색 시간 복잡도 : O(NlogN+MlogN)
입력 받을 때 시간 초과 나는지 잘 봤어야 하는데 문제 읽으며 시간 복잡도 생각하는 것까지는 아직도 잘 못하겠다.
> jieun lee / 5월 5주차 / 1문제

- minjeong/[PG]/181851 전국 대회 선발 고사/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/181851" rel="nofollow">181851 전국 대회 선발고사</a>
순서가 있다는 TreeMap 을 사용해봤는데 다음엔 이런 문제 풀 때 그냥 깔끔하게 자료구조 하나 더 사용해야겠다...
**TreeMap 에서 첫번째에 저장된 값 꺼내는 방법**
```java
TreeMap<자료형, 자료형> map = new Treemap<자료형, 자료형>();
// getKey - int 라고 가정
int key = map.firstEntry().getkey();
// getValue - int 라고 가정
int value = map.firstEntry().getValue();
```
**첫번째 그 다음 요소를 꺼내고 싶을 때**
```java
// value 를 꺼내고 싶을 때
int second_value = map.higherEntry(map.firstEntry().getKey()).getValue();
```
사실 이 문제는 자바의 업그레이드 문법과 메소드에 익숙하면 깔끔하게 풀 수 있다. 그런데 나는 모름 ㅎㅋ 자바8에 살고 있는 나
> minjeong / 5월 5주차 / 2문제

- JIEUN/B10813.java
<a href="https://www.acmicpc.net/problem/10813" rel="nofollow">10813 공 바꾸기</a>
> #116
> jieun lee / 5월 5주차 / 3문제

- minjeong/[PG]/181830 정사각형으로 만들기/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/181830" rel="nofollow">181830 정사각형으로 만들기</a>
범위를 나누어 푸는 간단한 문제...
좀 더 간결한 풀이도 있지 않을까?
> minjeong / 5월 5주차 / 4문제 

- DONGHEON/[BOJ] 12852 1로 만들기 2
<a href="https://www.acmicpc.net/problem/12852" rel="nofollow">12852 1로 만들기 2</a>
#116 
DP 문제이다
이번주에 열심히 안풀었더니 문제 푸는게 너무 어렵다 다음 주부터는 꼭 안놓치고 다 풀어야 겠다
> dongheon choi / 5월 5주차 / 2문제

- DONGHEON/[BOJ] 1105 팔
<a href="https://www.acmicpc.net/problem/1105" rel="nofollow">1105 팔</a>
#116
그리드 방식으로 문제를 풀어주면 된다.
DP, 그리드는 다시 보면 너무 새롭다 재밌긴 한데 머리가 너무 아프다
> dongheon choi / 5월 5주차 / 3문제

- minjeong/[PG]/181909 접미사 배열/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/181909" rel="nofollow">181909 접미사 배열</a>
Arrays.sort 메서드에는 기본적으로 comparator 가 구현되어 있다는 게 생각이 나서, 직접 comparator를 구현할까 했다가 그냥 Arrays.sort 로 풀었다.
이 문제는 직접 comparator를 구현했으면 좀 더 복잡하고 어렵게 풀었을 것 같다. 다음엔 직접 구현해봐야지
> minjeong / 6월 1주차 / 2문제

- DONGHEON/[BOJ] 2178 미로탐색
<a href="https://www.acmicpc.net/problem/2178" rel="nofollow">2178 미로탐색</a>
#128
그래프 탐색 문제이다.
간만에 다시 풀어본 그래프 탐색 문제이다
> dongheon choi / 6월 1주차 / 1문제

- DONGHEON/[BOJ] 1654 랜선자르기
<a href="https://www.acmicpc.net/problem/1654" rel="nofollow">1654 랜선자르기</a>
#128 
이분 탐색 문제이다. 
실버 문제로 재활을 하고 있는데 이제는 슬슬 다시 골드 문제를 시작해야겠다
> dongheon choi / 6월 1주차 / 2문제

- DONGHEON/[BOJ] 14719 빗물
<a href="https://www.acmicpc.net/problem/14719" rel="nofollow">14719 빗믈</a>
#128
투포인터 문제이다.
간만에 난이도가 좀 있는 문제를 하니 어렵다 ㅠㅠ
> dongheon choi / 6월 1주차 / 3문제

- minjeong/[PG]/120924 다음에 올 숫자 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120924" rel="nofollow">120924 다음에 올 숫자</a>
등차수열은 두 숫자 간의 차이가 모두 같아야 하고 조건에서 등차수열과 등비수열이 아닌 경우는 없다고 하였으니, 차이를 비교한 뒤 같으면 등차수열의 값을 구하는 공식을  차이가 같지 않으면 등비수열을 구하는 공식을 적용하여 풀이했다.
사실 이 문제 이렇게 쉬울지 몰랐다
> minjeong / 6월 1주차 / 4문제

- minjeong/[PG]/120887 k의 개수 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120887" rel="nofollow">120887 k의 개수</a>
예전에 풀다 만 문제라서 그 때 코드가 남아있었는데, 그때는 숫자로만 해결해보고 싶어서 while에 나눗셈 연산을 사용했다.
근데 어쨌건 해결이 안된 방법이기 때문에 오늘 문자열로 고쳐서 해당하는 값과 일치하는지 체크하는 방식으로 다시 풀어봤다. easy
근데 갈수록 내 코드가 더러워지는 것 같다 깔끔하게 푸는 방법이 없을까...
> minjeong / 6월 1주차 / 5문제 

- DONGHEON/[PGS] 298516 한 해에 잡은 물고기 수 구하기
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/298516" rel="nofollow">한 해에 잡은 물고기 수 구하기</a>
#142 
date format을 이용한 문제이다. sqld 공부하면서도 못봤던 친구를 문제를 풀면서 사용하여보았다
> dongheon choi / 6월 2주차 / 1문제

- JIEUN/B6603.java
<a href="https://www.acmicpc.net/problem/6603" rel="nofollow">6603 로또</a>
> #142 
백트래킹 합시다.
백트래킹 공부합시다.
화이팅.
> jieun lee / 6월 2주차 / 1문제

- DONGHEON/[BOJ] 13335 트럭
<a href="https://www.acmicpc.net/problem/13335" rel="nofollow">133335 트럭</a>
#128
큐를 이용하여 문제를 해결하면 되는 문제이다.
문제를 풀면서 어디선가 풀어본적이 있다고 생각했는데 프로그래머스에 같은 문제가 존재했던거 같다.
> dongheon choi / 6월 2주차 / 2문제

- DONGHEON/[BOJ] 16194 카드 구매하기 2
<a href="https://www.acmicpc.net/problem/16194" rel="nofollow">16194 카드 구매하기 2</a>
> ex) #142 
DP의 간단한 문제이다.
DP도 어느 정도 문제를 풀어 보다보니 약간의 흐름이 보이는 것 같다.
> dongheon choi / 6월 2주차 / 3문제

- JIEUN/P164672.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/164672">164672 조건에 부합하는 중고거래 상태 조회하기</a>
> #142
> jieun lee / 6월 2주차 / 4문제

- minjeong/[PG]/120884 치킨 쿠폰 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120884" rel="nofollow">120884 치킨 쿠폰</a>
치킨 1마리당 쿠폰 1장이기 때문에 남은 쿠폰을 치킨에 포함 시켜 계산해야 한다고 생각하고 풀었다.
식을 세워봤을 때 
```
chicken = chicken / 10 + chicken % 10;
```
이렇게 나와서 시도해봤는데, 남은 쿠폰과 치킨을 시킬 때 동시에 연산을 하면 안되는 문제였다. 
저 식 그대로 하면 치킨 쿠폰 9개 가지고 있고 1마리 시켜서 바로 10장 채워 계산하는 꼴이 됨... 
그래서 쿠폰과 결과를 먼저 선언하고 마지막에 치킨을 재할당 하는 방식으로 바꿔야했다.
```
int coupon = chicken % 10;
answer += chicken / 10;
chicken = coupon + chicken / 10;
```
계속 왜 안되지 하면서 이 문제에 1시간 이상을 쓴 듯 하다... 풀이는 간단했지만 순서가 생각했던 만큼 단순하지 않았다. 앞으로 컴퓨터처럼 더 사고 해야 될 듯 ㅜ
> minjeong / 6월 3주차 / 2문제

- DONGHEON/[BOJ] 1743 음식물 피하기
<a href="https://www.acmicpc.net/problem/1743" rel="nofollow">1743 음식물 피하기</a>
#152
DFS 문제이다 .
자꾸 한동안 알고리즘을 안풀게 되어서 다시 재활만 하는 거 같다 이제 제대로 시작해야겠다.
> dongheon choi / 6월 3주차 / 1문제

- JIEUN/P120892.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120892" rel="nofollow">120892 암호 해독</a>
> #152 
1학기 때 0단계 다 풀기 도전하던 시기에 풀었던 문제다.
지금 보니 그 때가 내 알고리즘의 정상이었던 것 같기도 하다...
A 따고 급속도로 퇴화하여 다시 IM도 못하는 사람이 됐다... 이거 맞나?
> jieun lee / 6월 3주차 / 2문제

- minjeong/[PG] 12930 이상한 문자 만들기 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/12930" rel="nofollow">12930 이상한 문자 만들기</a>
1. 단어마다 짝수 홀수 를 계산해야함. (이거 제대로 안 봐서 오래 걸림 ;; )
2. 하나 이상의 공백 문자로 구분됨.
하나 이상의 공백 문자로 구분되기 때문에 공백 문자를 만날 때마다 idx 를 홀수로 설정하여 그 뒤에 단어가 오는 경우 짝수 인덱스 부터 계산할 수 있게 해주었다.
모든 단어의 인덱스는 0부터 시작하기 때문에 짝수로 계산해주어야 하기 때문이다.
이게 뭐라고 이렇게 오래 걸렸지../
> minjeong / 6월 3주차 / 4문제

- minjeong/[PG]/120913 잘라서 배열로 저장하기 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120913" rel="nofollow">120913 잘라서 배열로 저장하기</a>
인덱스 번호는 n 보다 실제로 하나 작은 n-1 까지 채워지고 끊어진다.
따라서 인덱스 i-1 % n == 0 으로 기준을 두고 계산을 했다. 
이걸 풀면서 String[] s = new String[]; 문자열을 선언할 때 초기화 하는 방법을 찾아봤는데 딱히 없는 것 같았다. ㅜ 
new String[] 이라고 문자열 배열로 선언을 하게 되면 참조형 변수이기 때문에 null 로 초기화가 된다.
따라서 문자열 배열을 초기화 해주는 로직이 들어가게 된다.
쉬운 게 더 어려운 느낌...
> minjeong / 6월 3주차 / 5문제

- JIEUN/B2178.java
<a href="https://www.acmicpc.net/problem/2178" rel="nofollow">2178 미로 탐색</a>
> #167 
알고리즘 코드부터가 아니라 이론부터 다시 보기 시작했다.
겨우 하나 정리 끝냈는데 이해하고 코드로 다시 보고 하는 과정이 너무 귀찮다.
이걸 어떻게 이겨내나 고민이다. 그래도.. 해야지...
> jieun lee / 7월 1주차 / 1문제

- DONGHEON/[PGS] 599036 아픈 동물 찾기
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/59036" rel="nofollow">아픈 동물 찾기</a>
#167 
기본적인 sql 문제이다
이제부터는 제대로 알고리즘 문제를 다시 풀어 봐야겠다 이러다가 dfs도 까먹겠어~
> dongheon choi / 7월 1주차 / 1문제

- minjeong/[PG]/142086 가장 가까운 같은 글자 찾기 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/142086" rel="nofollow">142086 가장 가까운 같은 글자 찾기</a>
HashMap 에 글자와 인덱스를 저장하고 갱신하는 방법으로 풀어봤다!
문제만 읽었을 때는 미련하게 배열만 사용하려고 했었는데 해쉬맵 쓰니까 뚝딱이다
> minjeong / 7월 1주차 / 3문제

- JIEUN/B24444.java
- JIEUN/B24480.java
<a href="https://www.acmicpc.net/problem/24480" rel="nofollow">24480 알고리즘 수업 - 깊이 우선 탐색 2 </a>
> #167 
알고리즘 수업 깊이 우선 탐색 1과 유사
> jieun lee / 7월 1주차 / 3문제

- JIEUN/B24444.java
<a href="https://www.acmicpc.net/problem/24444 " rel="nofollow">24444 알고리즘 수업 - 너비 우선 탐색 1 </a>
> #167 
초기화하는 걸 계속 까먹어서 할 때 순서를 무조건 입력 -> 초기화 -> 그래프 구성 -> 정렬 -> 탐색 으로 정했다.
저거 생각하면서 하니까 덜 빼먹는 것 같다.
> jieun lee / 7월 1주차 / 4문제

- JIEUN/B24445.java
<a href="https://www.acmicpc.net/problem/24445" rel="nofollow">24445 알고리즘 수업 - 너비 우선 탐색 2</a>
>#167
> jieun lee / 7월 1주차 / 5문제

- JIEUN/b7576.java
<a href="https://www.acmicpc.net/problem/7576" rel="nofollow">7576 토마토</a>
> #181 
바이블 토마토로 무한회귀.
> jieun lee / 7월 2주차 / 2문제

- JIEUN/B1753.java
- JIEUN/B7569.java
<a href="https://www.acmicpc.net/problem/1753 " rel="nofollow">1753 최단경로</a>
> #181 
PriorityQueue를 사용하여 최소 비용의 정점을 선택.
선택된 정점의 인접 정점을 탐색하며, 현재 정점을 거쳐 가는 비용이 더 적은 경우 dist를 업데이트하고 큐에 추가.
다익스트라 : 가중치가 있는 그래프에서 한 정점에서 다른 모든 정점으로의 최단 경로를 찾는 데 효과적이다.
우선순위 큐 : 현재까지 알고 있는 최단 거리 중 가장 짧은 거리의 정점을 선택하는 것에 효과적임. 다익스트라랑 쓰면 효율성 굿!
으악
> jieun lee / 7월 2주차 / 3문제

- JIEUN/B7569.java
<a href="https://www.acmicpc.net/problem/7569" rel="nofollow">7569 토마토</a>
> #181 
7576 토마토의 3차원 배열 버전. 
어렵다!
> jieun lee / 7월 2주차 / 4문제

- JIEUN/B16953-1.java
<a href="https://www.acmicpc.net/problem/16953" rel="nofollow">16953  A->B</a>
> #181 
/*
큐에서 요소를 하나씩 꺼내어 현재 값과 현재 단계 수를 확인.
현재 값이 B와 같다면, 현재 단계 수를 반환.
현재 값에 가능한 연산(2배, 1 추가)을 수행하여 큐에 추가.
새로 추가된 값이 B보다 작거나 같을 때만 큐에 넣기.
*/
BFS로 이런 문제도 풀 수 있었다는 걸 다시 이해.
> jieun lee / 7월 2주차 / 5문제

- JIEUN/B1330.c
<a href="https://www.acmicpc.net/problem/1330" rel="nofollow">1330 두 수 비교하기</a>
> #193 
if문 써서 두 수를 비교하는 거다.
근데 이제 c언어를 곁들인.
> jieun lee / 7월 3주차 / 1문제

- JIEUN/B9498.c
<a href="https://www.acmicpc.net/problem/9498" rel="nofollow">9498 시험 성적</a>
> #193 
숫자를 영어 문자로 변경해주면 된다.
> jieun lee / 7월 3주차 / 2문제

- JIEUN/B2941.java
<a href="https://www.acmicpc.net/problem/2941" rel="nofollow">2941 크로아티아 알파벳</a>
>#203
*
작성자 : 이지은
작성일시 : 2024-07-31, 수, 22:57
입력 : 크로아티아 알파벳 (최대 100글자)
출력 : int 몇 개의 크로아티아 알파벳?
조건 : 단어에 몇 개의 크로아티아 알파벳이??
c- , dz= , d- , lj, nj, s= , z=
문제풀이 : 각 단어가 들어가는 횟수를 세자.
어떻게? 해당하는 단어를 찾으면 걔 빼고 뒤부터 돌아야되잖아.
해시맵으로 특정 단어 등장 횟수를 세면 되려나.
아니지 리플레이스올해서 단일 문자 치환을 해서 길이를 세면 되나.
음...
*/
[해시맵 vs replaceAll]
```
해시맵 사용의 한계
해시맵은 키-값 쌍 저장하고 조회할 때 매우 효율적임. 근데 이 문제는 단어에서 특정 문자열 패턴 찾아서 대체하는 작업이 필요함.
해시맵의 역할: 해시맵을 사용하면, 키로 패턴 저장하고 그 값을 대체할 값으로 매핑할 수 있음. 예를 들어, croatianAlphabets.put("c=", "c"); 같은 식으로 사용함.
제약: 해시맵 사용하면 단어에서 해당 패턴을 일괄적으로 대체할 수 없고, 각 패턴을 일일이 확인하면서 작업해야 함. 패턴이 존재하는지 확인하고, 그 패턴 찾아서 반복적으로 적용하는 비효율적인 루프 발생할 수 있음.
```
```
replaceAll의 장점
replaceAll은 문자열에서 특정 패턴을 찾아 대체하는 작업을 단순화해줌.
패턴 매칭과 치환: replaceAll 메서드는 …
```
> jieun lee / 8월 1주차 / 1문제

- DONGHEON/[BOJ] 1068 트리
<a href="https://www.acmicpc.net/problem/1068" rel="nofollow">1068 트리</a>
> ex) #203 
ArrayList<ArrayList<Integer>> 형식으로 자료구조를 만들어서 문제를 풀었다. 
이전에 풀었던 문제를 다시 보면서 풀었는데 간만에 푸는거라 잘 생각이 안나서 왜 이렇게 풀었었는지를 중점으로 다시 공부를 하면서 다시 풀어봤다. 생각보다 심각한 상태인것 같아 빠르게 재활에 들어가야 겠다.
> dongheon choi / 8월 1주차 / 1문제

- DONGHEON/[BOJ] 2293 코인1
<a href="https://www.acmicpc.net/problem/2293" rel="nofollow">2293 코인1</a>
> ex) #203 
DP 문제로 이중 for 문 안에서 DP를 계산해주며 문제를해결했다.
조금씩 재활을 해가고 있다 ㅠㅠ
> dongheon choi / 8월 1주차 / 2문제

- DONGHEON/[BOJ] 2294 동전2
<a href="https://www.acmicpc.net/problem/2294" rel="nofollow">2294 동전2</a>
> ex) #203 
priority queue 를 사용해서 어제 동전 1과 비슷하게 문제를 해결하면된다.
다시 푸는 문제인데도 쉽지않다 ㅠㅠㅠ
> dongheon choi / 8월 1주차 /3문제 

- B1316.java
<a href="https://www.acmicpc.net/problem/1316" rel="nofollow">1316 그룹 단어 체커</a>
> #203 
작성자 : 이지은
작성일시 : 2024-08-2, 금, 23:20
입력 :
출력 : int
조건 : 그룹 단어의 개수 출력
그룹 단어란, 각 문자가 연속해서 나타나는 경우만.
예, cccaaazzzb 는 c,a,z,b가 연속, aabbccb 는 b가 떨어져있기 때문에 그룹 아님.
문제풀이 :
한 문자가 이전 문자와 같으면 계속 진행 이대로 끝나면 그룹 단어.
이전 문자와 다르고 & 나온 적 있다면 그룹 단어 아님.
[HashSet]
자바 컬렉션 프레임워크 중 하나.
중복된 요소를 허용하지 않는 집합(Set) 데이터 구조.
중복된 요소 허용 안 함: HashSet은 동일한 요소를 두 번 이상 저장하지 않기 때문에 어떤 요소가 이미 집합에 존재하는지 쉽게 확인할 수 있다.
순서가 없음: HashSet은 요소들을 특정 순서대로 저장하지 않기 때문에 저장된 요소들의 순서는 예측할 수 없다.
빠른 접근: 내부적으로 해시 테이블을 사용하여 요소를 저장하기 때문에, 삽입, 삭제, 검색 연산이 평균적으로 O(1) 시간 복잡도를 가진다.
null 값 허용: HashSet은 null 값을 하나만 저장할 수 있다.
[HashSet을 사용하는 이유]
HashSet은 특정 요소가 이미 존재하는지 빠르게 확인해야 하는 경우 매우 유용하다. 예를 들어, 이 문제처럼 그룹 단어 문제에서 각 문자가 이미 등장했는지 확인하는 데 사용할 수 있다! 
문제풀이 떠올리는 게 쉽지 않다!
> jieun lee / 8월 1주차 / 2문제

- JIEUN/B25206.java
<a href="https://www.acmicpc.net/problem/25206" rel="nofollow">25206 너의 평점은</a>
> #203 
작성자 : 이지은
작성일시 : 2024-08-3, 토, 22:11
입력 : 과목명, 학점, 등급 (20줄 => 과목의 수 고정)
출력 :
조건 : 전공평점 = (학점 * 과목평점)의 합 / 학점의 총합
p인 과목은 계산 제외
문제풀이 : 해쉬맵으로 등급별 평점을 묶자.
HashMap<String, Double> 등급 키, 평점 값.
각 줄을 공백 기준으로 분리.
해쉬맵의 복습!
며칠 전 정리했던 해쉬맵 문제였다.
바로 떠올리긴 했는데 어떻게 써야할 지 고민한 후 풀 수 있었다.
공백 기준으로 스플릿하는 것도 떠올렸는데 그거랑 해쉬맵을 연결해서 생각하는 걸 제대로 하지 못해서 시간을 소요했다.
> jieun lee / 8월 1주차 / 3문제

- DONGHEON/[BOJ] 1107 리모컨
<a href="https://www.acmicpc.net/problem/1107" rel="nofollow">1107 리모컨</a>
#203 
브루트 포스를 통해 math.min 을 통해  가장 가까운 숫자를 찾은 후 값을 계산해 주면 된다.
오히려 브루트 포스 문제가 이렇게 풀어도 되나 싶어서 풀기가 어려운거 같다.
> dongheon choi / 8월 1주차 / 5문제

- JIEUN/B1193/B1193.java
<a href="https://www.acmicpc.net/problem/1193" rel="nofollow">1193 분수 찾기</a>
> #203 
급하게 풀었다..!!!
> jieun lee / 8월 1주차 / 4문제

- JIEUN/B9506.java
<a href="https://www.acmicpc.net/problem/9506" rel="nofollow">9506 약수들의 합</a>
> #217 
입력 받은 숫자 n의 약수를 구해서, 약수의 합이 n과 같으면 완전수임. 약수를 구할 때 n의 절반까지만 검사하면 됨. 완전수면 약수를 나열하고, 아니면 "n is NOT perfect." 출력함.
완전수는 자기 자신을 제외한 모든 약수의 합이 자기 자신과 같은 수임. 예를 들어 6은 1, 2, 3의 합이 6이어서 완전수임.
입력 받은 숫자가 완전수인지 검사하고, 맞으면 약수를 나열하고, 아니면 "n is NOT perfect." 출력하는 간단한 프로그램임.
> jieun lee / 8월 2주차 / 1문제

- minjeong/[PG]/181913 문자열 여러 번 뒤집기 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/181913" rel="nofollow">181913 문자열 여러 번 뒤집기</a>
커밋메시지 잘못 올라갔는데 바꾸는 페이지가 안 보여서 그냐 ㅇ 올린다...
> minjeong / 8월 2주차 / 2문제 

- minjeong/[PG]/12911 다음 큰 숫자 /src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/12911" rel="nofollow">12911 다음 큰 숫자</a>
- 2진수로 만드는 과정에서 1의 개수를 카운트하기
- 도출된 1의 개수가 같은지 비교하기
- 같다면 반복문을 멈추고 값을 반환한다. 다르다면 계속 이어감
문제 풀다가 1의 개수는 세지도 않고 냅다 reverse 시키려고 하다가 아 맞다! 하고 돌아왔다.
> minjeong / 8월 2주차 / 3문제

- JIEUN/B19532.java
<a href="https://www.acmicpc.net/problem/19532" rel="nofollow">19532 수학은 비대면강의입니다 </a>
> #217 
수학은 비대면 강의가 맞쥐
> jieun lee / 8월 2주차 / 2문제 

- DONGHEON/[BOJ] 1241 머리 톡톡
<a href="https://www.acmicpc.net/problem/1241" rel="nofollow">1241 머리 톡톡</a>
> ex) #217 
2중 for 문을 사용하여 문제를 해결하였다.
예전에 풀었던 문제들을 다시 풀고 있는데 생각보다 너무 쉬운 문제라 당황하였다.
> dongheon choi / 8월 2주차 / 2문제

- DONGHEON/[BOJ] 1744 수묶기
<a href="https://www.acmicpc.net/problem/1744" rel="nofollow">1744 수묶기</a>
> ex) #217 
곱하기의 성질을 이용한 문제이다. 큰수끼리 곱하면 더욱 더 커지는 것을 이용해 priority queue에 넣어서 문제를 해결했다.
이때 음수끼리 곱하면 양수가 되기에 음수용 pq와 양수용 pq를 구분하여 사용하였다.
이런 수학 문제도 재미있는거 같다.
> dongheon choi / 8월 2주차 / 4문제

- JIEUN/B2839.java
<a href="https://www.acmicpc.net/problem/2839" rel="nofollow">2839 설탕 배달</a>
> #217 
큰 봉지부터 사용: 최소 봉지 개수를 구하기 위해 가능한 5킬로그램 봉지를 최대한 사용. 남은 무게를 3킬로그램 봉지로 채우기.
반복적으로 5킬로그램 봉지를 줄임: 만약 남은 무게가 3킬로그램 봉지로 나누어 떨어지지 않는다면, 5킬로그램 봉지를 하나 줄이고 다시 계산.
최적화: 과정을 반복하며 3킬로그램 봉지로 딱 맞게 떨어지거나, 5킬로그램 봉지를 모두 줄였는데도 남은 무게가 3킬로그램 봉지로 채워지지 않으면 -1을 출력한다!
> jieun lee / 8월 2주차 / 3문제

- DONGHEON/[BOJ] 11000 강의실 배정
<a href="https://www.acmicpc.net/problem/11000" rel="nofollow">11000 강의실 배정</a>
> ex) #217
comparable 을 implments 해서 class 를 생성해주었다 그 후 그리디 알고리즘으로 문제를 해결하였다.
전에 풀었던 문제를 풀어보다 보면 내가 이걸 어찌 풀었었나 신기할때가 많은 것 같다.
> dongheon choi / 8월 2주차 / 5문제

- JIEUN/B2798.java
<a href="https://www.acmicpc.net/problem/2798" rel="nofollow">2798 블랙잭</a>
> #217 
마음의 안식처 브론즈...
> jieun lee / 8월 2주차 / 4문제

- DONGHEON/[BOJ] 1976 여행가자
<a href="https://www.acmicpc.net/problem/1976" rel="nofollow">1976 여행가자</a>
#231 
그래프 탐색으로 문제를 해결했다.
이 문제에서는 도시가 200개 밖에 안되기 때문에 2차원 배열로 문제를 해결했지만 좀 더 늘어나거나 한다면 다른 자료구조를 사용하여 문제를 해결해야할것 같다.
> dongheon choi / 8월 3주차 / 2문제

- JIEUN/P120812.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120812" rel="nofollow">120812 최빈값 구하기</a>
> #231 
최빈값을 구해요~
최빈값 1개일 때 구하기 
최빈값이 여러 개일 때 구하기
최빈값을 처음에 sort로 처리하려고 했는데 그렇게 하면 너무 효율이 떨어져서 그냥 for문 돌려서 찾는 걸로 바꿨다. 
무환 회귀자가 존재한다.. 바로 나.
프로그래머스 0단계 다시 조진다.
> jieun lee / 8월 3주차 / 1문제

- JIEUN/P120815.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120815" rel="nofollow">120815 피자 나눠 먹기 (2)</a>
>  #231
아 레벨 잘못 씀.....
> jieun lee / 8월 3주차 / 2문제

- JIEUN/P120822.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120822" rel="nofollow">120882 문자열 뒤집기</a>
> #231 
문자열을 배열로 만들고 배열을 뒤집어서 뒤집어진 문자열을 출력할 것.
1. 반환 타입에 대한 고찰 : void 와 int[], String[] 에 대해서.. 
2. 배열을 문자열로 만드는 5가지 방법.
1. Sring.join()
2. StringBuilder
3. Arrays.toString()
4. Collectors.joining()
5. 반복문으로 직접 변환
기초 약한 건 어디서든 티가 난다...
> jieun lee / 8월 3주차 / 3문제

- DONGHEON/[BOJ] 10026 적록색약
<a href="https://www.acmicpc.net/problem/10026" rel="nofollow">10026 적록색약</a>
#231 
넓이 우선 탐색인 DFS로 문제를 해결했다. 
다음 문제는 BFS를 사용하는 문제로 풀어봐야겠다.
> dongheon choi / 8월 3주차 / 3문제

- JIEUN/P128040.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120840" rel="nofollow">120840 구슬을 나누는 경우의 수</a>
> #231 
조합을 활용해서 푸는 문제다.
int, long 으로 했을 때 계속 정수 오버플로우로가 나서 실패하는 문제들이 생겼다.
BigInteger 사용해서 해결했다.
> jieun lee / 8월 3주차 / 4문제

- minjeong/[BJ]/4344 평균은 넘겠지/src
<a href="https://www.acmicpc.net/problem/4344" rel="nofollow">4344 평균은 넘겠지</a>
평균을 넘은 (초과) 학생들의 비율을 구하는 문제이다.
처음에 문제 잘못 읽어서 평균 구함...ㅣㅣ
담주엔 진짜 재귀 공부한다;;
> minjeong / 8월 3주차 / 5문제

- JIEUN/P120816.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120816" rel="nofollow">120816 피자 나눠 먹기 (3)</a>
> #231 
사람%조각수==0 이면 사람/조각수.
사람%조각수!=0 이면 사람/조각수 +1.
// 삼항 연산자를 사용하여 한 줄로 결과 반환
return (n % slice == 0) ? n / slice : n / slice + 1;
요즘은 문제를 일단 풀어놓고 그게 진짜 최선의 풀이가 맞는지 확인하는 시간을 가지고 있는데, 이건 문제가 요구하는 대로 푼 문제는 맞지만 더 간결하려면 삼항 연산자도 쓸 수 있다길래 그것도 한번 해봤다.
> jieun lee / 8월 3주차 / 5문제

- minjeong/[PG]/70129 이진 변환 반복하기/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/70129" rel="nofollow">70129 이진 변환 반복하기</a>
while 으로 돌렸을 때 시간 초과났다. 다른 사람들 보니까 재귀로 풀었다고 해서 재귀로 뜯어고침... 
이제는 진짜 물러설 곳이 없다. level 0, 1 거의 다 하고 진짜진짜진짜 알고리즘 재활 훈련을 할 때가 된 것이다. 재귀 조합 다 디져따
> minjeong / 8월 4주차 / 1문제

- JIEUN/P120844.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120844" rel="nofollow">120844 배열 회전시키기</a>
> #247
왼쪽, 오른쪽일 때의 메서드를 따로 빼서 풀어줬다.
0단계 절반이 보인다. 이거 한방에 100문제씩 넘게 풀던 기개가 이젠 없다...
> jieun lee / 8월 4주차 / 1문제

- JIEUN/P120850.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120850" rel="nofollow">120850 문자열 정렬하기 (1)</a>
> #247 
Character.isDigit(ch) 메서드를 사용하여 현재 문자가 숫자인지 확인했다.
> jieun lee / 8월 4주차 / 2문제

- minjeong/[PG]/134240 푸드 파이트 대회/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/134240" rel="nofollow">134240 푸드 파이트 대회</a>
StringBuffer 메서드를 안 쓰고, 가운데를 기점으로 앞 뒤로 문자를 추가하는 방식으로 풀어보려고 했다.
근데 배열이 아니라 그런지 내 뜻대로 뭐가 잘 안됨... 결국 StringBuffer의 힘을 빌려 구현했다.
이거 쉬운 것이지만 원하는 대로 풀고 싶어서 시간이 좀 걸렸다...
> minjeong / 8월 4주차 / 4문제

- JIEUN/P120852.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120852" rel="nofollow">120852 소인수분해</a>
> #247 
현실에서 소인수분해를 한다고 하면, 2부터 나눠볼 거 같음. 그리고 계속해서 0으로 나눠지는 수로 나눠보겠지.
=> 더이상 2로는 나눌 수 없을 때 그 다음 숫자로 넘어가게 되는 거야.
음 그렇면 그걸 코드로 어떻게 해봐야 하는 걸까?
근데 이럴 경우에 몇이 나눌 수 있는 최대 숫자인 거야? 아무래도 √n 여기까지가 최대. 
Set을 사용해서 중복된 소수를 제거한 후, 결과를 배열로 변환하여 반환했다.
이렇게 하면 모든 소수를 바르게 처리하고, 가장 큰 소수가 먼저 리스트에 들어가는 문제를 방지할 수 있다.
[블로그에 정리 중](https://myrecord98.tistory.com/entry/JAVA-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-Lv0-%EC%86%8C%EC%9D%B8%EC%88%98%EB%B6%84%ED%95%B4)
> jieun lee / 8월 4주차 / 3문제

- DONGHEON/[BOJ] 11492 통나무 건너뛰기
<a href="https://www.acmicpc.net/problem/11297" rel="nofollow">11497 통나무 건너뛰기</a>
#247 
Math.max 와 Arrays.sort를 이용하여 수를 찾아내어 풀어주면 되는 문제이다.  StringBuilder를 간만에 써보는 느낌이다.
> dongheon choi / 8월 4주차 / 3문제

- JIEUN/P120834.java
- JIEUN/P120860.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120834" rel="nofollow">120834 외계 행성의 나이</a>
> #247 
10, 100, 1000의 자리일 때마다 케이스를 나눠서 생각했었다.
그런데 이 방법 말고 더 좋고 간결한 코드가 있을 거라 계속 생각을 하다가 자릿수에 상관없는 코드로 방식을 바꾸어 풀이했다.
나머지 연산 (%): 이 연산을 사용하면 숫자의 가장 마지막 자릿수를 추출할 수 있다.
예를 들어, 123 % 10은 3을 반환함.
나눗셈 연산 (/): 이 연산을 사용하면 숫자의 마지막 자릿수를 제거할 수 있다.
예를 들어, 123 / 10은 12를 반환함.
> jieun lee / 8월 4주차 / 4문제

- JIEUN/P120860.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120860" rel="nofollow">120860 직사각형 넓이 구하기 </a>
> ex) #이슈번호, #이슈번호
오늘은 사족 없이
> jieun lee / 8월 4주차 / 5문제

- JIEUN/P120861.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120861" rel="nofollow">120861 캐릭터의 좌표</a>
> #263
갈 수 있는 보드의 크기 안에서 문자열에 맞는 방향으로 이동하도록 로직을 짰다.
위치, 방향 전환 이런 것만 나오면 무조건 델타 방식으로 쓰기 시작했는데... 그게 더 복잡한 경우가 오히려 꽤 있었다.
이번에도 굳이 배열을 써가며 방향을 전환할 필요가 없는 문제여서 코드를 바꿨다.
[블로그 정리](https://myrecord98.tistory.com/entry/JAVA-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-Lv0-%EC%BA%90%EB%A6%AD%ED%84%B0%EC%9D%98-%EC%A2%8C%ED%91%9C)
> jieun lee / 8월 5주차 / 1문제

- JIEUN/P120866.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/120866" rel="nofollow">120866 안전지대</a>
> #263
8방 탐색으로 푸는 문제.
2차원 배열 탐색의 시작.
1이면 지뢰, 0이면 아니.
> jieun lee / 8월 5주차 / 2문제

- minjeong/[PG]/12973 짝지어 제거하기/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/12973" rel="nofollow">12793 짝지어 제거하기</a>
스택을 이용하여 풀었다.
스택의 가장 상단에 위치한 데이터와 현재 집어 넣어야 하는 데이터를 비교하여 같으면 pop 을 하고 다르면 push 를 했다.
문자열의 길이만큼 반복을 실행한 뒤 스택이 비어 있으면 성공이고 스택에 남아있으면 실패이다.
배열로 구현해서 풀어볼까?
> minjeong / 8월 5주차 / 1문제

- JIEUN/B1475.java
<a href="https://www.acmicpc.net/problem/1475" rel="nofollow">1475 방 번호</a>
> #263 
//0~9 까지 한세트
// 6과 9는 뒤집어서 사용할 수 있음.
6과 9는 대체 가능하므로 합산하여 반올림한다.
6일 때, 9일 때 처리해준다.
오랜만에 백준
> jieun lee / 8월 5주차 / 3문제

- minjeong/[PG]/132267 콜라문제/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/132267" rel="nofollow">132267 콜라 문제</a>
마트에 빈 병 a 개를 주면 콜라 b 개로 교환해준다. n 개의 빈병을 가지고 있을 때, a 보다 n이 작아질 때까지 교환을 반복하여 마실 수 있는 총 콜라의 수는 얼마인가?
예전에 풀었던 치킨 쿠폰이랑 문제가 비슷하다.    
<br>
**🔑 keypoint**
테스트 케이스에 대해 직접 계산을 해보며 계산식을 세웠는데, 계산식은
- 반환되는 콜라 `returns = n / a *b`
- 남은 빈병 `remains = n % a`
- 가지고 있는 빈병의 수 `n = returns + remains`
- 마신 콜라의 총 개수 `cnt = cnt + returns`
이다. 
요즘은 알고리즘 풀 때 쉬운 문제라도 손으로 적으면서 하고 있는데 확실히 도움이 되는 것 같다.
> minjeong / 8월 5주차 / 3문제

- JIEUN/G1454730(ing)
<a href="https://k-digital.goorm.io/learn/lecture/29413/%EB%B9%84%ED%83%80%EC%95%8C%EA%B3%A0-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%B4%88%EA%B8%89%EB%B6%80%ED%84%B0-%EC%A4%91%EA%B8%89%EA%B9%8C%EC%A7%80/lesson/1454730/%EC%9D%B8%EC%8B%B8%EA%B0%80-%EB%90%98%EA%B3%A0-%EC%8B%B6%EC%9D%80-%EB%AF%BC%EC%88%98-2" rel="nofollow">인싸가 되고 싶은 민수</a>
> #263 
1. 약수 구하기
2. 약수의 빈도수 구하기 (1 제외)
3. 최대 빈도 (동일일 경우 작은 약수로)
민수야 미안하다 인싸 못 시켜주겠다.
이거 무슨 짓을 해도 테스트 케이스 11개 중에 8개만 맞는다.
몇 번을 풀었는데 아직도 해결 못 했다.. 덜 풀고 올리는 문제는 이게 처음이다...
답이 뭘까.. 테케 공개해라
> jieun lee / 8월 5주차 / 4문제

- minjeong/[GRM]/1454730 인싸가 되고 싶은 민수/src
<a href="https://level.goorm.io/exam/49089/%EC%9D%B8%EC%8B%B8%EA%B0%80-%EB%90%98%EA%B3%A0-%EC%8B%B6%EC%9D%80-%EB%AF%BC%EC%88%98/quiz/1" rel="nofollow">1454730 인싸가 되고 싶은 민수</a>
그리디하게 푸는 문제였다. 
사실 계속 메모리에 대한 런타임 에러가 나서 계속 효율적으로 푸는 방법에 대해서 생각해봤다. 
**틀린 풀이**
``` java
import java.io.*;
class Main {
public static void main(String[] args) throws Exception {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
String[] input = br.readLine().split(" ");
int a = Integer.parseInt(input[0]);
int b = Integer.parseInt(input[1]);
int[] divisor = new int[b+1];
// a부터 b까지의 수
for(int i = a; i <= b; i++){
// 현재 해당하는 수의 약수 구하여 배열에 넣기
for(int j = 1; j <= i; j++){
if(i % j == 0) divisor[j]++;
}
}
int answer = 0;
int max = 0;
for(int i = 2; i < divisor.length; i++){
if(divisor[i] > max) { …
```
> minjeong / 8월 5주차 / 4문제

- JIEUN/B1919.java
<a href="https://www.acmicpc.net/problem/1919" rel="nofollow">1919 애너그램 만들기</a>
> #263
빈도의 차이로 찾는다.
브론즈인데 왜 어려워 큰1
> jieun lee / 8월 5주차 / 5문제

- minjeong/[GRM]/29413 교수님의 과제폭탄/src
<a href="https://k-digital.goorm.io/learn/lecture/29413/%EB%B9%84%ED%83%80%EC%95%8C%EA%B3%A0-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%B4%88%EA%B8%89%EB%B6%80%ED%84%B0-%EC%A4%91%EA%B8%89%EA%B9%8C%EC%A7%80/lesson/1454747/%EA%B5%90%EC%88%98%EB%8B%98%EC%9D%98-%EA%B3%BC%EC%A0%9C-%ED%8F%AD%ED%83%84-3" rel="nofollow">29413 교수님의 과제 폭탄</a>
보자마자 스택으로 풀면 되겠는데? 라고 생각했다.
자꾸 틀려서 종이에 풀이를 천천히 적었는데 시작날짜, 마감날짜 둘 다 오름차순 정렬을 해야하는데 내가 바보같이 마감날짜를 내림차순 정렬해놨었다. 어쩐지!
이거 푼다고 1시간 30분 정도 썼는데, 제출했더니 12개 중에 3개가 실패했다고 뜬다. ㅜㅜ 반례를 못 찾겠는데 도대체 뭘까...
> minjeong / 9월 1주차 / 1문제

- minjeong/[GRM]/49111 외계인과 용돈기입장/src
<a href="https://level.goorm.io/exam/49111/%EC%99%B8%EA%B3%84%EC%9D%B8%EA%B3%BC-%EC%9A%A9%EB%8F%88%EA%B8%B0%EC%9E%85%EC%9E%A5/quiz/1" rel="nofollow">49111 외계인과 용돈기입장</a>
**문제 요약**
특정 구간 동안 수입 및 지출이 적자인지 흑자인지 구하는 문제
1. N, M은 최소 1, 최대 200,000
2. 각 수입 및 지출은 최소 -10억, 최대 +10억
3. a, b는 최소 1, 최대 N
🔑 **keypoint**
1. 시간복잡도를 고려하여 구간합으로 문제 풀이하기
2. 구간합에 대한 자료구조 사용 시, 범위는 Long 혹은 long 으로 할 것
아 이거 잘 풀어놓고 구간합 배열을 long 으로 설정 안 해서 한참 찾았다...
> minjeong / 9월 1주차 / 3문제

- JIEUN/B10773.java
<a href="https://www.acmicpc.net/problem/10773" rel="nofollow">10773 제로</a>
> #277 
스택 문제다.
스껄 스껄
> jieun lee / 9월 1주차 / 1문제

- minjeong/[BJ]/1009 분산처리/src
<a href="https://www.acmicpc.net/problem/1009" rel="nofollow">1009 분산처리</a>
모듈러 연산을 이용하여 풀었다. 
잠 자고 싶다...
> minjeong / 9월 1주차 / 4문제

- minjeong/[BJ]/1110 더하기 사이클/src
<a href="https://www.acmicpc.net/problem/1110" rel="nofollow">1110 더하기 사이클</a>
while 에 조건 걸어서 빠져나오기!
좀 더 깔끔하게 푸는 풀이를 생각해봐야겠다.
> minjeong / 9월 1주차 / 5문제

- JIEUN/B1874.java
<a href="https://www.acmicpc.net/problem/1874" rel="nofollow">1874 스택 수열</a>
> #277 
스택과 자료구조로 풀 수 있는 문제다.
> jieun lee / 9월 1주차 / 2문제

- JIEUN/B2493.java
<a href="https://www.acmicpc.net/problem/2493" rel="nofollow">2493 탑</a>
> #277 
이 문제는 Scanner 로 하면 무조건 시간 초과나는 문제이다.
난 스캐너 안 써서 상관없었다.
> jieun lee / 9월 1주차 / 3문제

- minjeong/[PG]/340206 각도 합치기/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/340206" rel="nofollow">340206 각도 합치기</a>
한 줄만 고쳐서 정답으로 만드는 디버깅 문제였다. 의외로 한줄만 고치는 게 더 어렵고 오래 걸린다..
> minjeong / 9월 2주차 / 1문제

- minjeong/[PG]/340204 병과분류/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/340204" rel="nofollow">340204 병과분류</a>
빈칸 채우기 문제...
> minjeong / 9월 2주차 / 2문제

- minjeong/[PG]/340203 심폐소생술/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/340203" rel="nofollow">340203 심폐소생술</a>
디버깅 문제
내일은 그래프 탐색 공부해야겠당
> minjeong / 9월 4주차 / 1문제

- DONGHEON/[BOJ] 24042 횡단보도
<a href="https://www.acmicpc.net/problem/24042" rel="nofollow">24042 횡단보도</a>
#296 
다익스트라를 사용한다.  ArrayList<ArrayList<>>로 값을 받을 class와 priorityQueue에 사용할 class를 두개 만들어 주어 상황에 맞게 사용할 수 있게 하였다. 주어진 값의 시간은 int 의 범위를 넘어 날 수 있기에 priority에 사용하는 class를 만들때 인자 값과 DP 배열은 long으로 만들어 주었다. 
compareTo를 사용할 때 해당 메소드에서 Long값의 비교를 하려면 Long.compare를 사용하면 return 값을 int 로 받을 수 있다.
어려운 문제를 풀면 시간이 너무 순식간에 간다. 간만에 그래프 탐색 문제를 푸니까 재미있었다.
> dongheon choi / 9월 4주차 / 1문제

- DONGHEON/[BOJ] 2042 구간 합 구하기
<a href="https://www.acmicpc.net/problem/2042" rel="nofollow">2042 구간 합 구하기</a>
#296 
세그먼트 트리를 이용해서 문제를 해결하면 된다. 입력 값이 -2^63 ~ 2^63-1 의 범위 이기 때문에 이 부분을 주의하여 문제를 해결해야한다.
세그먼트 트리 : 부분 합의 시간 복잡도가 O(log n ) 이라 부분 합을 구할 때 사용하면 좋다. 많은 업데이트가 일어나게 되면 O(Mlog n) 으로 이때 쓰는 방법이 추가 적으로 존재 한다.
세그먼트 트리 언제가는 공부해봐야지 하고 사용을 해봤는데 아직 완벽하게 익히지 못한거 같다. 조금 더 공부하고 부분의 최소 값과 최대 값을 추가 적으로 공부해 봐야겠다.
> dongheon choi / 9월 4주차 / 2문제

- minjeong/[PG]/340200 닉네임규칙/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/340200" rel="nofollow">340200 닉네임규칙</a>
디버깅 문제
사실 오늘은 완탐 공부할랬는데 할 일이 많아졋다... 근데 이거 난이도 쉬운건데도 문제 5분은 들여다 보고 생각함.
> minjeong / 9월 4주차 / 2문제

- DONGHEON/[BOJ] 2268 수들의 합7
<a href="https://www.acmicpc.net/problem/2268" rel="nofollow">2268 수들의 합7</a>
#296
세그먼트 트리를 이용하여 문제를 해결하였다. 이번 문제는 값의 업데이트가 빈번하게 일어나는 문제라서 문제를 풀었는데도 ms1600 정도가 나왔다. 세그먼트 트리를 공부할 때 알아보니 lazy propagation 이라는 방식을 사용하면 업데이트에 있어서 속도를 개선할 수 있다고 하는데 나중에 공부를 해봐야겠다. 
세그먼트 트리도 일반 적인 그래프 탐색과 같이 한번 익혀두면 다음에 사용할 때는 크게 생각할 것 없이 사용하면 되는 것 같다.
문제는 추가적으로 쓸 수 있는 것이 많아 공부를 하면 할 수록 공부할 것이 늘어난다.
> dongheon choi / 9월 4주차 / 3문제

- DONGHEON/[BOJ] 10999 구간 합 구하기2
<a href="https://www.acmicpc.net/problem/10999" rel="nofollow">10999 구간 합 구하기2</a>
> ex) #296 
해당 문제는 변경되는 값이 범위로 주어진다. 이경우 일반적인 세그먼트 트리를 쓰더라도 update가 많이 발생해 시간 초과가 발생할 수 있음으로 Lazy Propagation을 사용해야 한다.
2일 정도 세그먼트 트리 문제를 안봤더니 그새 가물가물해져서 다시 복기하면서 문제를 풀었다. Lazy Propagation이 확실히 이해가 잘 안되는 부분이 많이 존재한다. 이걸 왜 이렇게 해야하지 싶은 부분도 많은데 코드를 읽다보면 아 이래서 그렇구나 하는 부분이 있어서 재미 있었던거 같다.
다음에는 최소 값 문제, 최대 값문제를 풀어봐야겠다. + 유니온앤 파인드
> dongheon choi / 9월 4주차 / 5문제

- minjeong/[BJ]/2606 바이러스/src
<a href="https://www.acmicpc.net/problem/2606" rel="nofollow">2606 바이러스</a>
DFS 를 사용하여 풀이하는 간단한 문제였다.
DFS 복습하기... 근데 이건 그냥 세뇌된 기억으로 푼 것 ㅓ같다... 내일은 진짜 그래프탐색으로 공부해봐야지
> minjeong / 10월 1주차 / 1문제

- DONGHEON/[BOJ] 2357 최솟값과 최댓값
<a href="https://www.acmicpc.net/problem/2357" rel="nofollow">2357 최솟값과 최댓값</a>
#304 
세그먼트 트리에서 최솟값과 최댓값을 구하는 것을 사용하여 문제를 해결하면된다.
기존의 세그먼트 트리에서 합을 구하는 것을 대소 관계를 비교하여 pair을 만들어 보내주는 식으로 코드를 바꾸어서 풀면 되지 않을까 싶어 해보았다.
문제는 풀리기는 했으나 속도가 생각보다 느린것 같아서 다른 사람들의 코드를 보고 고칠것이 있으면 고쳐봐야겠다.
어렵게 생각했는데 생각보다 기존의 세그먼트 트리와 크게 다를 바가 없어서 할만 했던거 같다.
재귀부분을 어느정도 파악하니까 수월하다.
> dongheon choi / 10월 1주차 / 1문제

- DONGHEON/[BOJ] 11505 구간합구하기
<a href="https://www.acmicpc.net/problem/11505" rel="nofollow">11505 구간 합 구하기</a>
#304 
세그먼트 트리와 문제 풀이 방식이 유사하다.
비슷하겠지 하고 문제를 풀었지만 구간 합보다 고려해야 하는 부분들이 많이 존재 했다. 합과 같은 경우는 update를 하는 과정에서 더하고 빼더라도 큰 문제가 존재하지 않았는데 구간 곱과 같은 경우 중간의 값을 0으로 변경하는 순간 복구가 불가능했다. 그래서 update를 진행하면 업데이트할 노드와 연관된 부모 노드들을 전부 재귀적으로 업데이트하는 방식으로 진행하였다
> dongheon choi / 10월 1주차 / 2문제

- DONGHEON/[BOJ] 1257 커피숍2
<a href="https://www.acmicpc.net/problem/1257" rel="nofollow">1257 커피숍2</a>
#304 
세그,먼트 트리를 이용하여 문제를 해결하면 된다.
문제가 너무 불친절했다. 문제 자체에 필요한 조건을 테스트 케이스 밑에 숨겨놔서 계속 실패를 하다가 겨우 문제를 해결했다.
조건 같은건 좀 문제안에 넣어 줬으면 좋겠다.
> dongheon choi / 10월 1주차 / 4문제

- DONGHEON/[BOJ] 5676 음주코딩
<a href="https://www.acmicpc.net/problem/5676" rel="nofollow">5676 음주 코딩</a>
#304
일반적인 세그먼트 트리의 곱 문제이다.
이 문제는 테스트 케이스를 여러개 주는데 몇개를 주는지 알려주지않아 어찌할줄 몰랐던 문제이다. while을 사용해서 입력값이 없을때 까지 돌리면 되는 간단한 해결방안이 있었다.
> dongheon choi / 10월 1주차 / 5문제

- DONGHEON/[BOJ] 10868 최솟값
<a href="https://www.acmicpc.net/problem/10868" rel="nofollow">10868 최솟값</a>
#313 
세그먼트 트리에서 최솟값을 찾아내면 되는 문제이다. 합이아니라 비교를 해서 최솟값을 저장하고 있으면 된다.
다른 문제를 풀다가 너무 시간이 부족해서 도망 온 문제이다. 내일은 풀던 문제를 마저 풀어야겠다.
> dongheon choi / 10월 2주차 / 1문제

- DONGHEON/[BOJ] 1615 교차수세기
<a href="https://www.acmicpc.net/problem/1615" rel="nofollow">1615 교차수 세기</a>
#313
우선 A 에 대해 수를 정렬해 준 후 tree에 B값에 맞는 위치에 순서대로  update시키면서 sum 값을 구하면 된다.
어제 고민했던거에 비해 최근에 풀어 본 유형과 매우 흡사했다. 문제 자체가 자바로는 메모리 문제로 풀이가 불가능하다고 하다;;;
혹시나 틀리게 풀었나 싶어 풀이를 찾아보니 풀이 과정 자체는 맞는 것 같다.
> dongheon choi / 10월 2주차 / 2문제

- DONGHEON/[BOJ] 12837 가계부(hard)
<a href="https://www.acmicpc.net/problem/12837" rel="nofollow">12837 가계부(hard)</a>
#313
세그먼트 트리를 이용해서 문제를 해결하면 된다
이번 문제는 update를 그냥 계속 더해주면 되는데 자꾸 새로운 값을 변경을 하다가 계속 틀렸다.
> dongheon choi / 10월 2주차 / 4문제

- JIEUN/B10407.java
<a href="https://www.acmicpc.net/problem/10407" rel="nofollow">10407 2 타워</a>
> #319 
제곱의 재귀.
입력 : 높이 H
출력 : H 높이의 2타워 값을 3으로 나눈 나머지를 출력.
문제점 : long으로 처리하기에도 값이 커서 오류가 남.
해결법 : BigInteger, 모듈러 사용해서 풀어야 함.
+) 수정
문제 이해를 잘못 했음.. 4층 : 3층 * 3층 이라고 생각했었음.
근데 그냥 제곱수를 계속 곱하는 거였다. 4층 : 2의 (((2^2)^2)^2) 임.
이렇게 되면 2일 때 빼고 나머지는 전부 나머지가 1일 수 밖에 없음.
BigInteger 로만 잘 맞춰주면 간단한 문제였다.
| **특징**            | **long**                                   | **BigInteger**                                  |
|---------------------|--------------------------------------------|-------------------------------------------------|
| **데이터 타입**     | 기본형 (primitive type)                    | 클래스 (객체)                                   |
| **저장 크기**       | 64비트 정수형 (8바이트)                     | 가변 길이 (필요한 만큼 메모리를 사용) …
> Jieun lee / 10월 4주차 / 3문제

- minjeong/[BJ]/24511 queuestack/src
<a href="https://www.acmicpc.net/problem/24511" rel="nofollow">24511 queuestack</a>
deque를 사용해서 푸는 문제이다. deque 를 사용하려면 로직이 살짝 복잡해질 것 같아서 그냥 풀었다.
테케는 다 맞았는데 시간초과 났다. 아무래도 deque를 직접 사용하지 않아서 그런 것 같아서 조만간 다시 풀어야 할 듯 하다.
> minjeong / 10월 4주차 / 1문제

- JIEUN/B2860.java
<a href="https://www.acmicpc.net/problem/2860" rel="nofollow">2860 종이에 숫자 쓰기</a>
> #324 
원래 풀던 문제가 죽어도 안 풀려서 이걸로 갈아탐..
그래서 풀이는 코드에 주석 다는 걸로 대신한다.
백준 24435 디버깅... 대체 어떻게 해야 풀릴래..?
다음에 진짜 죽었다..
> Jieun lee / 10월 5주차 / 1문제 

- minjeong/[BJ]/2903 중앙 이동 알고리즘/src
<a href="https://www.acmicpc.net/problem/2903" rel="nofollow">2903 중앙 이동 알고리즘</a>
사각형의 개수를 R, 점의 개수를 P, 진행되는 회차를 N이라고 할 때,
가장 기본 상태인 사각형 하나를 0회차라고 가정한다.
|N=0|N=1|N=2|N=3|...|
|:--:|:--:|:--:|:--:|:--:|
|R=1|R=4|R=16|R=64|...|
|P=4|P=9|P=25|P=81|...|
이런식으로 나온다.
한 눈에 봤을 때 규칙을 찾기 어려워 모두 2의 거듭제곱으로 바꾸어 확인해보았다.
|N=0|N=1|N=2|N=3|
|:--:|:--:|:--:|:--:|
| R = $(2^0)^2$ | R = $(2^1)^2$ | R = $(2^2)^2$ | R = $(2^3)^2$ |
| P = $(2^0+1)^2$ | P = $(2^1+1)^2$ | P = $(2^2+1)^2$ | P = $(2^3+1)^2$ |
임을 알 수 있었다.
따라서 N일 때, 
R = $(2^N)^2$ , P = $(2^N+1)^2$ 이다.
수학 카테고리에 들어가 있는 문제였다.
> minjeong / 10월 5주차 / 1문제

- DONGHEON/[PGS] 42587 프로세스
- DONGHEON/[PGS] 87390 n^2 배열 자르기
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/42587" rel="nofollow">42587 프로세스</a>
#324 
PriorityQueue 를 사용하면 되는 문제이다.
아이디어를 떠올리지 못해서 전부다 계산을 하는 식을 짜려다가 아닌것 같다는 생각이 들었다.
간단하게 푸는 방법이 있나 찾아 봤더니 단순하게 풀면 되는 문제였다.
for문을 돌려 가면서 위치를 맞춰주면 되는 문제였다.
> dongheon choi / 10월 5주차 / 1문제

- minjeong/[BJ]/2720 세탁소 사장 동혁/src
<a href="https://www.acmicpc.net/problem/2720" rel="nofollow">2720 세탁소 사장 동혁</a>
거스름돈 동전의 개수를 구하는 문제
money 를 저장하지 않으면 값이 제대로 나오지 않는다.
> minjeong / 10월 5주차 / 2문제

- DONGHEON/[PGS] 64065 튜플
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/64065" rel="nofollow">64065 튜플</a>
#324 
StringTokenizer를 사용해서 { } , 를 기준으로 모두 나눠주었다. 해당 문제는 집합에서는 각 원소들이 위치가 상관 없이 존재하기 때문에 어떤 원소가 가장 많이 나왔는지를 판단하여 결과 값에서 순서대로 넣어 주어야 했다.
더 쉽게 푸는 방법도 존재할 것 같지만 최근에 계속 pq를 써서 그런가 pq를 사용해서 푸는 방법 밖에 생각이 나지 않는다 ㅠㅠ
해쉬맵을 이용한 방법으로도 문제를 풀어 보았다. 코드 자체는 많이 간단해 졌지만 실행시간은 더 늘었다. 업데이트를 진행할때마다 hashmap에서 찾아오는 시간이 더 걸려서 그런거 같다.
프로그래머스 점점 익숙해지니까 재밌는거 같다.
> dongheon choi / 10월 5주차 / 3문제

- minjeong/[BJ]/28279 덱2/src
<a href="https://www.acmicpc.net/problem/28279" rel="nofollow">28279 덱2</a>
deque 사용하는 방법을 익히는 문제였다.
시간초과가 자꾸 났는데, StringBuilder 를 사용하여 해결했다.
시간초과나서 오래 걸림...
> minjeong / 10월 5주차 / 3문제

- JIEUN/B24453.cpp
<a href="https://www.acmicpc.net/problem/24453" rel="nofollow">24453 디버깅</a>
> #324 
자바로 하면 죽어도 안 풀리고...
내가 살다살다 알고리즘을 c++로 다 풀어본다...
이거는 진짜 계속 풀어봐야겠다.
> Jieun lee / 10월 5주차 / 2문제

- DONGHEON/[PGS] 17677 [1차] 뉴스 클러스터링
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/17677" rel="nofollow">[1차] 뉴스 클러스터링
</a>
#324 
정규식을 사용하기 위해 split을 다시 공부했다. 디테일한 부분에서 모르는 부분들이 존재를 했어서 시간이 꽤 오래 걸렸다. 
split을 통해 문자열을 자르고 다중 집합이기에 중복되는 문자열을 세어주기 위해 각 문자들을 hashMap에 <String, Integer>로 저장을 한 다음 중복되는 것이 있을경우 int 값을 1씩 늘려 주었다.
그후 두 해쉬 맵을 비교해 가며 수를 세어 합집합에 대한 값을 구하였다.
문자열을 마스터 했었다고 생각했는데 한동안 안 풀다가 보니까 메소드들도 잘 기억이 안나고 정규식도 버벅 걸리는 모습을 보았다. 문자열 문제를 좀 더 완벽하게 가다듬어야겠다.
>  dongheon choi / 10월5주차 / 4문제

- minjeong/[BJ]/11866 요세푸스 문제0/src
<a href="https://www.acmicpc.net/problem/11866" rel="nofollow">11866 요세푸스 문제0</a>
큐를 활용한 배열 문제라고 해서 풀어봤다.
원형큐처럼 구현하는 문제인 것 같았다.
이번주 큐스택마슷허하고 담주에 다시 완탐이랑 친해지기 해야지.
> minjeong / 10월 5주차 / 4문제

- minjeong/[PG]/340202 [PCCE 기출문제] 6번 물 부족/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/340202?language=java" rel="nofollow">340202 물 부족</a>
간단한 수식 구현하는 디버깅 문제였다.
그런데 막상 다른 사람 코드 디버깅 하려니까 어딜 손대야 할지 몰라서 노트 꺼내서 직접 식을 세워봤다.
> minjeong / 10월 5주차 / 5문제

- DONGHEON/[PGS] 132265 롤케이크자르기
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/132265" rel="nofollow">132265 롤케이크자르기</a>
#324
일단 하나의 배열에 모든 토핑의 수를 세어 주었다.
토핑을 순서대로 하나씩 빼면서 다른 배열에 넣어주고 토핑의 수를 세어 주어 비교하였다.
작년 초에 풀던 문제들의 느낌이 나서 재미있었다.
> dongheon choi / 10월 5주차 / 5문제

- JIEUN/B7576_new.java
<a href="https://www.acmicpc.net/problem/7576" rel="nofollow">7576 토마토</a>
> #338 
조건 :
1 : 익은 토마토
0 : 익지 않은 토마토
-1 : 토마토 없음
익은 토마토는 익지 않은 토마토에 영향을 준다.
토마토가 스스로 익는 경우는 없다.
입력 :
m n (상자의 크기)
상자에 담긴 토마토 정보 (n개의 줄, 줄마다 m개)
출력 :
토마토가 모두 익을 때까지의 최소 날짜
(이미 모두 익어있다 : 1, 모두 익지 못하는 상태 : -1)
이 문제가 나쁜 건.. m n 으로 입력 주고 배열은 [n][m] 으로 만들게 한다는 거다...
> Jieun lee / 11월 1주차 / 1문제

- DONGHEON/[PGS] 132265 [3차] 압축
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/17684" rel="nofollow">17684 [3차] 압축</a>
#338 
Hashmap을 사전이라 생각하고 문제를 해결했다. string을 순차적으로 돌면서 해당 substring이 이미 해쉬에 있는지 없는지 체크하며 문제를 풀었다.
substring은 0번 인덱스의 string을 가져 오려면 substring(0,1) 과 같이 써야 해서 for문에서 조건을 줄떄 index가 넘거나 적어서 계속 머리가 아팠다. 프로그래머스로 오류 찾는거 너무 어렵다 ㅠㅠ. 끽하면 출력범위를 넘었다 그러고 ㅠㅠ
> dongheon choi / 11월 1주차 / 1문제

- DONGHEON/[PGS] 49994 방문길이
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/49994" rel="nofollow">49994 방문길이</a>
#338 
그래프 탐색 문제이다. 이 문제와 같은 경우에는 좌표를 방문배열 처리를 해야하는 것이 아니라 좌표 사이의 길을 방문 배열 처리를 해야해서 방문 배열을 두가지로 나눠서 체크 했다. 오른쪽 왼쪽으로 움직을때를  체크하는 방문 배열과 위 아래로 움직일 때를 처리하는 방문 배열 두가지를 사용하면 그 다음부터는 조건에 맞게만 작성하면 되는 문제이다.
그래프 탐색은 언제나 풀면 풀다가 지치는것 같다.
> dongheon choi / 11월 1주차 / 3문제

- JIEUN/B4179.java
<a href="https://www.acmicpc.net/problem/4179" rel="nofollow">4179 불!</a>
> #338 
조건:
불은 각 지점에서 네 방향으로 확산.
지훈이와 불은 매 분마다 한칸씩 수평 또는 수직으로만 이동. (대각선 불가)
입력:
r c (행, 열)
미로행
#: 벽
.: 지나갈 수 있는 공간
J: 지훈이의 미로에서의 초기위치 (지나갈 수 있는 공간)
F: 불이 난 공간
J는 입력에서 하나만 주어진다.
출력:
가장 빠른 탈출시간
(불보다 빨리 탈출할 수 없는 경우 : IMPOSSIBLE)
불과 지훈이를 따로 따로 봐주면서 비교한다.
> Jieun lee / 11월 1주차 / 3문제

- DONGHEON/[PGS] 169198 당구 연습
- DONGHEON/[PGS] 250135 아날로그 시계
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/250135" rel="nofollow">250135 아날로그 시계</a>
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/169198" rel="nofollow">169198 당구 연습</a>
#346 
시침이 한바퀴 돌려면은 총 43200초가 걸린다. 이를 이용해 비례식을 세워 초침은 1초에 720을 움직이고 분침은 12 시침은 1을 움직인다고 생각하고 문제를 풀었다. 문제가 고려해야 하는 점이 많은 반면에 나올만한 엣지케이스들이 전부 테스트케이스로 주어져서 상황을 고려하여 문제를 해결해주면 된다.
내가 처음에 고려하지 않았던 문제는 다음과 같다.
1. 정확히 시간이 딱 떨어질 때만을 고려했던점 -> 범위로 바꾸면서 문제를 해결
2. 한바퀴를 넘어갈때를 고려하지 않았던점
3. 범위로 바꾸게 되면서 정확하게 맞아떨어지고 난 다음번의 계산에서 한번더 결과가 추가되는점
좋은 문제라고 보기는 어려울 것 같지만 주어진 테스트케이스들에서 어떤 것들을 고려해야 하는지를 찾아내는 능력을 기르는 데에는 좋은 문제라고 생각을 한다.
각 점에서 비례식을 세워서 점이 벽면에 닿는 위치를 구해서 풀었다.
틀렸다.
이문제는 그렇게 풀면 틀린다.ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
진짜 이런식의 문제는 문제가 잘못 된거 같다.
그냥 계산해선 풀려면 다양한 방법이 존재하지만 코드로 풀면 하나의 방식만이 필요한데 그 방식을 알려주지 않아서 틀리게 하는건 매우 …
> dongheon choi / 11월 2주차 / 2문제

- DONGHEON/[PGS] 42577 전화번호 목록
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/42577" rel="nofollow">42577 전화번호 목록</a>
#348 
배열을 sort 해준 다음 i번째 문자열과 i+1번째 문자열을 비교해주면된다.
처음에는 String 배열의 sort 방식에 대해 착각하고 있었어서 배열을 sort한다음 2중 for문으로 모든 비교를 해주었었다.
자꾸 시간초과가 발생하여 찾아본 결과 어차피 sort한 순간 유사도가 비슷한것들 부터 정렬이 되기때문에 단일 for문으로도 충분하게 문제를 풀 수가 있었다.
찾아보는 과정에서 String[] 의 sort에 대해 알 수 있었고 또한 string.startsWith(String) 이라는 메소드가 존재한다는 것을 배웠다.
> dongheon choi / 11월 2주차 / 3문제

- DONGHEON/[PGS] 17687 [3차] n진수 게임
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/17687" rel="nofollow">17687 [3차] n진수 게임
</a>
#348 
Integer.toString(number , 진수) 를 사용하면 숫자를 쉽게 진수에 맞게 변경을 할 수 있다. 이를 이용해서 문제를 해결했다.
진수 변경
10진수 -> n진수
Integer.toString(num , n)
n진수 -> 10진수 (String 형태여야한다)
Integer.parseInt( "num" , n)
char to String  
1. ""+char 
2. String.valueOf(char)
대문자 변경 (자꾸 까먹어서 작성)
"abcd".toUpperCase();
문자열 문제가 알고 있어야하는 메소드들이 많은 거 같다.
> dongheon choi / 11월 2주차 / 4문제

- DONGHEON/[PGS] 42626 더 맵게
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/42626" rel="nofollow">42626 더 맵게</a>
#346 
모든 수가 K를 넘어야 함으로 가장 작은 수를 확인을 해줄 필요가 있었다. 이를 PriorityQueue를 이용해서 해결을 하였다.
코드도 지저분하고 실행시간도 생각보다  큰거 같아서 다른 방법이 있을까 싶어 확인을 해봤더니 코드를 조금 더 깔끔하게 하는 방법은 존재했는데 실행시간은 거의 비슷했다.
> dongheon choi / 11월 2주차 /5문제

- minjeong/[PG]/340201 버스/src
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/340201" rel="nofollow">340201 버스</a>
빈칸 문제, 조금만 생각해보면 금방 풀 수 있다.
> minjeong / 11월 3주차 / 2문제

- DONGHEON/[PGS] 49993 스킬트리
- DONGHEON/[PGS] 92341 주차 요금 계산
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/49993" rel="nofollow">49993 스킬트리</a>
#352 
hashmap에 skill 의 char를 key로 index를 value로 지정해서 넣어두고 skill_tree를 비교할때마다 boolean[]를 생성하여 확인해주었다.
hashmap 문제 중에서도 간단한 문제인것 같다.
Map을 사용하여 문제를 해결했다. 코드가 생각보다 길게 나와서 다른 사람의 풀이를 보았더니 배울점이 많이 존재했다.
TreeMap을 사용했더라면 pair class 생성과 PriorityQueue를 사용하지 않더라도 문제 풀이가 가능하였고 시간을 저장하는 방법에 대해서도 배울 점이 존재했다. 
treemap을 모르거나 시간 저장에 대해서 아이디어가 없으면 코드가 나처럼 길어질 수 밖에 없는 문제인것 같다
> dongheon choi / 11월 3주차 / 1문제

- DONGHEON/[PGS] 131704 택배상자
- DONGHEON/[PGS] 154538 숫자 변환하기
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/131704#" rel="nofollow">131704 택배상자</a>
#352 
stack 을 사용해서 문제를 해결했다. 코드 길이를 줄여보려고 줄이다가 조건을 삭제하게 되서 찾는데 시간이 오래 걸렸다.
stack도 간만에 보니까 반갑다.
처음 문제를 봤을 때는 DP를 사용해서 풀어야 하나 싶었지만 범위를 넘어서면 그냥 버려도 되는 문제이기에 PQ를 이용해서 문제를 풀기로 했다.
class 생성과 PQ 사용 연습을 하는데 좋은 문제인것 같다.
> dongheon choi / 11월 3주차 / 2문제

- JIEUN/B10026.java
<a href="https://www.acmicpc.net/problem/10026" rel="nofollow">10026 적록색약</a>
> #352 
**추후 수정**
> Jieun lee / 11월 3주차 / 1문제

- DONGHEON/[PGS] 12900 2 X N 타일링
- DONGHEON/[PGS] 17686 [3차] 파일명 정렬
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/17686 " rel="nofollow">17686 [3차] 파일명 정렬
</a>
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/12900" rel="nofollow">12900 2Xn 타일링</a>
#351 
11월 20일 풀이
class를 생성하여 comparable을 implements 해주어서 priorityqueue에 넣어주었다. 숫자와 같은 경우에는 크게 고민할 것 없이 01001 이더라도 Integer.parseInt를 사용하면 앞쪽 0은 제거 된 채로 나온다. "01001" -> 1001 추가로 고민해 볼 만한 것은 a1 과 a01을 같은 파일명으로 본다는 것이다. 이때 priorityqueue에서 들어간 순서를 보장 해주지 않기 때문에 class를 생성 할때 들어간 순서를 확인할 수 있는 order를 생성해 주었다.
priorityqueue 같은 레벨의 개체에 대해서도 들어간 순서를 보장해주지 않는다.
그래서 class를 생성할 때 order를 만들어 주어 compareTo 할때 사용하도록 만들었다. 
문제를 애해를 잘못해서 많이 돌아갔다.  tail은 정렬을 할때 기준 점이 되지 않지만 tail 끼리도 비교를 해야된다고 생각을 해서 문제 해결에 시간을 소모했다.
priorityQueue를 사용할때도 들어간 순서가 보장이 되는 줄 알았는데 그렇지 않더라 ㅠㅠ
피보나치문제를 풀듯이 풀면 되는 문제이다. …
> dongheon choi / 11월 3주차 / 3문제

- JIEUN/P12980.java
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/12980?language=java" rel="nofollow">12980 점프와 순간 이동</a>
> #352 
문제는 엄청 긴데 사실 별 거 아니다.
홀수면 점프하고 짝수면 순간이동하라는 것일 뿐.
> Jieun lee / 11월 3주차 / 2문제

- DONGHEON/[PGS] 42883 큰 수 만들기
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/42883#" rel="nofollow">42883 큰 수 만들기</a>
#352 
그리디 방식으로 계속 비교해가며 풀면된다.
String의 메소드와 StringBuffer의 메소드를 헷갈려서 시간이 좀 걸렸다
> dongheon choi / 11월 3주차 / 4문제

- DONGHEON/[PGS] 12899 124 나라의 숫자
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/12899" rel="nofollow">12899 124 나라의 숫자</a>
#352 
3으로 나머지와 몫을 구해가며 상황에 맞게 추가해주면 된다.
StringBuilder insert 를 사용했다. 
주의 해야할 점은 몫이 0이 나왔을 때만 좀 고려해서 문제를 풀면 된다.
> dongheon choi / 11월 3주차 / 5문제

- DONGHEON/[PGS] 77885 2개 이하로 다른 비트
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/77885#" rel="nofollow">77885 2개 이하로 다른 비트</a>
#364 
long 을 toString 을 이용하여 2진법으로 바꿔 준후 뒤에서 부터 0인 경우를 찾았다.
만약 n번째의 수가 0인 경우가 있다면 n번째 자리를 1로 n+1자리의 수를 0으로 바꿔 준 후 (뒤에서 부터 0을 찾아 왔기 때문에 n+1 번째 자리수는 무조건 1이다. n == String.length() 인 경우 다르게 처리 ) parseLong을 통해서 원래 대로 바꿔 주었다.
이 문제와 같은 경우에는 원래 수 보다 큰 경우만을 보면 되기 때문에 고민할 것이 많지 않은 문제였다.
> dongheon choi / 11월 4주차 / 1문제

- DONGHEON/[PGS] 42884 단속카메라
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/42884#" rel="nofollow">42884 단속카메라</a>
#364
route[n] 을 오름차순으로 정렬하고 두가지 기준으로 구별해주면된다.
1. startPoint가 이전 차량의 endpoint보다 작은지 큰지 구별
2. 크다면 answer++ 해주고 기준점을 현재차량의 endpoint로 갱신
3. 작다면 이전 endpoint와 현재 차량의 endpoint를 비교해주고 현재 차량의 endpoint가 더 작다면 기준점을 현재차량의 endpoint로 갱신
백준에서 풀어봤던 문제인데 3번째 조건이 기억이 안나 테스트케이스를 추가해보고 문제를 해결했다.
> dongheon choi / 11월 4주차 / 3문제

- DONGHEON/[BOJ] 15903 카드합체놀이
<a href="https://www.acmicpc.net/problem/15903" rel="nofollow">15903 카드합체놀이</a>
#369
pq를 사용하여 2수를 뽑아서 더한 수를 두번 넣으면 되는 문제이다.
조건을 제대로 파악하지 못하여 수가 int 범위를 벗어날 수도 있다는 것을 놓쳤었다.
> dongheonchoi / [힙] / 카드합체놀이 / Silver 1

- JIEUN/B12761.java
<a href="https://www.acmicpc.net/problem/12761" rel="nofollow">12761 돌다리</a>
>#369
1. 큐에 저장 (현재위치, 이동횟수)
2. 종료조건 : 동규 위치(현재위치) == 주미 위치
3. bfs 탐색, 방문 처리
이거 테스트 케이스는 맞는데 계속 실패하는 게 뭔가 문제가 있나본데... 모르겠음.
+) pos에서 스카이콩콩으로 이동하는 경우 넣을 때 -a, -b를 깜빡하고 안 넣음 ^^
무사히 해결.
> leeje0506 / [BFS] 돌다리 / 실버 1

- JIEUN/B15903.java
<a href="https://www.acmicpc.net/problem/15903" rel="nofollow">15903 카드 합체 놀이</a>
> #369
가장 작은 두개의 카드를 꺼내고 더하는 것을 반복하는 로직.
우선순위큐 사용해서 가장 작은 수들을 가장 빠르게 가져올 수 있도록 함.
+추가) 푸시하려고 할 때 NullPointerException에 대한 경고가 떴다. 이거 고려해서 카드가 무조건 2개 이상 선택되어야 하고, 큐에 값이 비어있을 때의 예외처리를 추가했다.
석환아 남 시킬거면 카드 게임 하지 마라.
> leeje0506 / [힙] 카드 합체 놀이 / 실버 1

- minjeong/[BJ]/12761 돌다리
<a href="https://www.acmicpc.net/problem/12761" rel="nofollow">12761 돌다리</a>
BFS로 풀기
사실 이번주에 너무 몸이 안 좋았어서 저번에 풀어놨던 풀이 보면서 다시 공부했다. 인접리스트로 풀어야지~ 라고 생각했는데 BFS는 크게 다를 게 없었던 것 같다. 게다가 이문제 일차원이라서 굳이 인접리스트로 어렵게 풀 필요가 없는,,
> dolmeengii / [DFS/BFS] 돌다리 / 실버1

- minjeong/[BJ]/15903 카드 합체 놀이
<a href="https://www.acmicpc.net/problem/15903" rel="nofollow">15903 카드 합체 놀이</a>
오름차순 정렬을 해서 더하고 또 그 중에 작은 값으로 오름차순 정렬을 해야 해서 우선순위 큐를 사용하여 풀 수 있다.
마음이 급해서 풀이 보고 이해해서 풀었다. 건강 관리 잘하기^^ 다음 주기 돌아올 때 다시 풀어봐야지.
> dolmeengii / [힙] 카드 합체 놀이 / 실버 1

- minjeong/[BJ]/16113 시그널
<a href="https://www.acmicpc.net/problem/16113" rel="nofollow">16113 시그널</a>
규칙에 따라 천천히 풀이를 하면 된다.
규칙을 잘 보고 0~9 의 숫자에 해당하는 판별 로직을 짜야겠다고 생각했다.
그런데 뭐가 자꾸 안돼서 (런타임에러) 답지 봤다. 나는 StringTokenizer를 사용해서 하고 있었는데 다른 사람 풀이 보니까 그냥 String으로 한번에 해결했다... 이것도 StringTokenizer 써서 다시 풀이해야겠다.
> dolmeengii / [시뮬레이션/구현] 시그널 / 실버 1

- DONGHEON/[BOJ] 11687 팩토리얼0의갯수
<a href="https://www.acmicpc.net/problem/11687" rel="nofollow">11687 팩토리얼 0의 갯수</a>
#376 
이분 탐색을 사용하여 문제를 풀면 된다. 0의 갯수를 세는 방법을 떠올리면 쉽게 풀수 있는 문제이다.
> dongheonchoi / [이분탐색] / 팩토리얼0의갯수 / 실버1

- DONGHEON/[boj] 1946 신입사원
<a href="https://www.acmicpc.net/problem/1946" rel="nofollow">1946 신입사원</a>
#376 
그리디 방식의 문제이다. 나는 문제자체를 이해하는데 시간이 좀 걸렸고 푸는 방법자체는 간단하다.
> dongheonchoi / [그리디] / 신입사원 / 실버1

- DONGHEON/[boj] 1932 정수 삼각형
<a href="https://www.acmicpc.net/problem/1932" rel="nofollow">1932 정수 삼각형</a>
#376 
수를 어떤 식으로 저장할 건지 파악하면 쉽게 풀수 있는 문제이다.
> dongheonchoi / [DP] / 정수 삼각형 / 실버 1

- minjeong/[BJ]/1932 정수 삼각형
<a href="https://www.acmicpc.net/problem/1932" rel="nofollow">1932 정수 삼각형</a>
문제를 자세히 봐보니 DP + 탐색을 해서 풀어야 하는 문제였다.
탐색을 위에서부터 진행하면 너무 비효율적일 것 같았다.
맨 밑에 있는 줄을 배열에 저장해놓고, 거기서부터 최댓값을 DP 배열에 저장해나가는 식으로 구현하면 될 것 같음!
ㅜㅜ 미리미리 하자.
DP에 익숙하지 않아 풀이 보고 풀었다...
다음 주에 다시 풀어볼것.
> dolmeengii / [DP] 정수 삼각형 / 실버 1

- minjeong/[BJ]/1946 신입사원
<a href="https://www.acmicpc.net/problem/1946" rel="nofollow">1946 신입사원</a>
처음에는 이차원 배열로 풀이하려고 했는데, 너무 오래 걸릴 것 같았음.
그래서 다시 보니까 서류성적을 기준으로 정렬하여 면접성적을 비교해 합불하면 됨!
서류 1등의 면접 성적을 변수에 할당하여 비교할 건데, 이때 서류 2등 이후의 성적을 차례로 비교할 것임.
서류 2등의 면접 성적과 서류 1등의 면접 성적을 비교했을 때 1등의 면접 성적이 더 높다면 1등 합격시키고, 서류 2등의 결과를 변수에 할당하여 이후 등수 사람들의 면접 성적과 비교함.
아아
> dolmeengii / [그리디] 신입사원 / 실버1

- minjeong/[BJ]/11687 팩토리얼 0의 개수
<a href="https://www.acmicpc.net/problem/11687" rel="nofollow">11687 팩토리얼 0의 개수</a>
기본 이분탐색 개념 + 어떻게 하면 0의 개수를 셀 수 있는지 잘 생각해보면 된다.
근데 나는 잘 생각 못 함 
내가 제일 싫어하는 유형의 문제였다. 그래서 풀이를 봤다.
> dolmeengii / [이분탐색] 팩토리얼 0의 개수 / 실버1

- minjeong/[BJ]/1421 나무꾼 이다솜
<a href="https://www.acmicpc.net/problem/1421" rel="nofollow">1421 나무꾼 이다솜</a>
풀이 보고 공부하며 풀이했다.
> dolmeengii /[완전탐색] 나무꾼 이다솜 / 실버 1

- minjeong/[BJ]/7562 나이트의 이동
<a href="https://www.acmicpc.net/problem/7562" rel="nofollow">7562 나이트의 이동</a>
최소 이동 횟수를 구하는 것이므로 BFS 로 풀기
우하하
> dolmeengii / [그래프] 나이트의 이동 / 실버 1

- minjeong/[BJ]/1446 지름길
<a href="https://www.acmicpc.net/problem/1446" rel="nofollow">1446 지름길</a>
다익스트라 공부하며 풀이보며 풀기.. 근데 예전에 이미 풀어봤더라?
> dolmeengii / [다익스트라] 지름길 / 실버 1

- DONGHEON/[BOJ] 2194 유닛이동시키기
<a href="https://www.acmicpc.net/problem/2194" rel="nofollow">2194 유닛이동시키기</a>
#390 
BFS를 사용하여 해결하면 되는 문제이다 .
풀면서 문제가 상당히 불친절하다는 것을 알았다. 그냥 행 번호라고 되어 있길래 이게 0부터 시작하는 행의 번호인지 아닌지를 문제를 풀던 도중에 깨달았다.
풀면서 실수한 부분은 이문제는 dfs로 푸니 틀린다. 시간초과 같은 것도 아니고 그냥 틀린다. 같은 방식 그대로 bfs로 푸니 바로 통과...
> dongheonchoi / [DFS/BFS] 유닛이동시키기 / 골드 4

- DONGHEON/[BOJ] 1715 카드 정렬하기
<a href="https://www.acmicpc.net/problem/1715" rel="nofollow">1715</a>
#390 
작은 수 부터 차례대로 계속해서 더해주면 된다.
먼저 더해지는 수는 반복적으로 더해지기 때문에 먼저 뽑아야한다는 점만 깨달으면 굉장히 쉽게 풀수 있는 문제이다.
> dongheonchoi / [힙] 카드 정렬하기 / 골드 4

- JIEUN/B14503.java
<a href="https://www.acmicpc.net/problem/14503" rel="nofollow">14503 로봇 청소기</a>
#390 
> ex) #이슈번호, #이슈번호
추후 수정.
> leeje0506 / [시뮬레이션] 로봇 청소기 / 골드 5

- JIEUN/B1715.java
<a href="https://www.acmicpc.net/problem/1715" rel="nofollow">1715 카드 정렬하기</a>
#390
> ex) #이슈번호, #이슈번호
추후 수정.
> leeje0506 / [힙] 카드 정렬하기 / 골드 4

- DONGHEON/[BOJ] 14503 로봇청소기
- [BOJ] 14503 로봇청소기
<a href="https://www.acmicpc.net/problem/14503" rel="nofollow">14503 로봇청소기</a>
#390 
시뮬레이션 문제 답게 조건을 만족시키는게 중요한 문제이다.
전에 풀어본적이 있었던 문제라 이번에는 좀 간편하게 풀수 있었다.
> dongheonchoi / [시뮬레이션] 로봇청소기 / 골드 5

- DONGHEON/[BOJ] 11000 강의실배정
<a href="https://www.acmicpc.net/problem/11000" rel="nofollow">11000 강의실 배정</a>
#390 
그리디 방식으로 문제를 풀면 된다. 시작하는 시간과 끝나는 시간을 하나로 묶어서 끝나는 시간이 다음의 시작 시간 보다 크면 1씩 값을 늘려주면된다.
> dongheonchoi / [그리디] / 강의실 배정 / 골드 5

- DONGHEON/[BOJ] 1915 가장 큰 정사각형
<a href="https://www.acmicpc.net/problem/1915" rel="nofollow">1915 가장 큰 정사각형</a>
#390 
DP를 사용해서 문제를 풀면된다.
이번 문제는 잘 이해가 가지 않아서 코드를 보고 문제를 해결했다 ㅠㅠ
> dongheonchoi / [DP] / 가장 큰 정사각형 / 골드 4

- JIEUN/B1504.java
<a href="https://www.acmicpc.net/problem/1504" rel="nofollow">1504 특정한 최단 경로</a>
> ex) #400 
이 문제에서 반드시 거쳐야 하는 두 정점이 있어서 다익스트라를 3번 실행했다.
1번 노드, v1노드, v2노드 로부터 최단거리를 구한 다음, v1, v2를 지날 수 있는 2가지 경우에 맞춰서 두가지 경로를 비교해서 최소값을 구했다.
그래프는 방향이 없는 양방향임. 즉, 간선이 양쪽으로 존재한다는 뜻.
풀다가 검색의 힘을 좀 빌렸수다.
> leeje0506 / [다익스트라] 특정한 최단 경로 / 골드 4

- JIEUN/B1062.java
<a href="https://www.acmicpc.net/problem/1062" rel="nofollow">1062 가르침</a>
> ex) #400 
anta ~ tica 형태로 만들어지지 않으면 읽을 수 없다.
antic 5개는 무조건 가르쳐야 단어를 읽을 수 있는 거다. => 모르면 읽을 수 없다 처리.
그 후에 남은 21개 중에 어떤 걸 골라야 최대로 읽는지를 판단한다. => 완탐(백트래킹)
- 모든 단어에서 anta, tica를 떼어내고 남은 글자를 조사한다. 
- 각 경우마다 읽을 수 있는 단어 개수를 세어 최댓값을 갱신해준다.
백트래킹(조합): 21개의 알파벳 중 K-5개를 선택하는 경우의 수 탐색
비트마스킹: 어떤 알파벳을 배웠는지를 빠르게 체크 가능
아니 무슨.. 그냥 표로 나눠줘... 못 가르칠 거면...
처음에 antic 를 무조건 알아야 하는 거라는 걸 인지 못해서 계속 풀리지 않았고, 그래서 지피티랑 대화 나누다보니까 저게 제일 중요하다는 걸 알았다.
> leeje0506 / [완전탐색] 가르침 / 골드 4

- JIEUN/B13023.java
<a href="https://www.acmicpc.net/problem/13023" rel="nofollow">13023 ABCDE</a>
> ex) #400 
방문한 노드를 체크, 탐색이 끝나면 방문한 노드를 다시 체크 해제(미방문 상태).
DFS 수행하고 깊이 4가 되면 1 출력 후 종료. 없으면 0 출력 후 종료.
예시에서.. 
5 5
0 1
1 2
2 3
3 0
1 4
0부터 시작하면 1, 3 중에 갈 수 있다.(깊이 1)
1로 간다면, 다음은 0,2,4 중에 갈 수 있다. (0은 방문, 깊이 2)
2로 간다면, 다음은 1,3 중에 갈 수 있다. (1은 방문, 깊이 3)
3으로 간다면, 0,2만 갈 수 있다. (0,2 모두 방문, 깊이 4, 종료)
이렇게 되면 친구 관계가 성립할 수 없다고 봤다.
어떻게 해야할 지 고민하다가 0이랑 친구인 애, 1이랑 친구인 애 이런 식으로 나눠서 생각해봤다. 결국 그 중에 한명이라도 아는 친구가 이어지면 되고, 아니면 종료한다. 모두가 이어지려면 깊이는 5여야 하고, 그 이하는 모조리 성립하지 않는다고 판단했다.
> leeje0506 / [그래프] ABCDE / 골드 5

- DONGHEON/[BOJ] 1062 가르침
<a href="https://www.acmicpc.net/problem/1062" rel="nofollow">1062 가르침</a>
#400
가르칠 수 있는 알바벳의 조합을 조합하여 어떤 조합이 가장 많이 학습할 수 있는 조합인지를 찾아내면 되는 문제이다.
간만에 조합을 이용한 문제를 풀어본거 같아서 재미있다.
> dongheonchoi / [완전탐색] / 가르침 / 골드 4

- DONGHEON/[BOJ] 13023 ABCDE
<a href="https://www.acmicpc.net/problem/13023" rel="nofollow">13023 ABCDE</a>
#400
인접행렬을 통해 연결된 길이가 5이상이 존재하는지를 확인해주면 되는 문제이다.
ArrayList를 행렬로 쓰는 것은 왜 익숙해지지가 않을까
> dongheonchoi / [그래프] / ABCDE / 골드 5

- minjeong/[BJ]/1062 가르침
<a href="https://www.acmicpc.net/problem/1062" rel="nofollow">1062 가르침</a>
으음~ 대충 할 줄 아는 문자 개수에 따라서 출력할 문자를 나누고, 그 이후에 문자를 체크해야겠다고는 생각했다.
풀이를 좀 생각해보다가 오늘이 끝나기 전에 문제를 해결하고 싶어 풀이를 봤다. 사실 많은 사람의 다양한 풀이가 있었지만 내가 이해하기 쉬운 방법은 백트래킹 + 조합의 방법이었다.
다음주부터는 자스로 문제 푸는 연습해야하는데...
> dolmeengii / [완전탐색] 가르침 / 골드 4

- DONGHEON/[BOJ] 1504 특정한최단경로
<a href="https://www.acmicpc.net/problem/1504" rel="nofollow">1504 특정한최단경로</a>
#400
다익스트라를 사용해 문제를 풀면된다.
시작점에서 거쳐가는 지점 .
거쳐가는 지점간의 거리.
끝까지의 거리를 계산하면된다.
풀이 과정은 생각한 방법이 맞았는데 inf를 설정하는 부분을 모르겠어서 찾아보고 문제를 풀었다.
> dongheonchoi / [다익스트라] / 특정한최단경로 / 골드 4

- minjeong/[BJ]/13023 ABCDE
틀림
<a href="https://www.acmicpc.net/problem/13023" rel="nofollow">13023 ABCDE</a>
이 문제, 내가 골라서 고를 때 어떻게 풀지 생각해보고 넣어놓은 문제다. 그런데 틀림. 틀려서 여기저기 다 찾아봄 뭐가 문제인지. 일단 이 전에는 가독성 안 좋게 for 문을 array[start].get(i) 이런 식으로 돌게 만들어놔서 그거 먼저 고침. 근데 이제는 뭐가 문제인지 몰겎다.
> dolmeengii / [그래프] ABCDE / 골드5

- DONGHEON/[BOJ] 2146 다리만들기
<a href="https://www.acmicpc.net/problem/2146" rel="nofollow">2146 다리 만들기</a>
#405
조건에 맞는 노드들은 모두 담은 뒤 계산하여 최소 거리를 구하였다.
> dongheonchoi / [DFS/BFS] / 다리 만들기 / 골드 3

- JIEUN/B11559.java
<a href="https://www.acmicpc.net/problem/11559" rel="nofollow">11559 뿌요뿌요</a>
> ex) #405 
내용없음.
> leeje0506 / [시뮬레이션] 뿌요뿌요 / 골드 5

- JIEUN/B2146.java
<a href="https://www.acmicpc.net/problem/2146" rel="nofollow">2146 다리 만들기</a>
> ex) #405
실패해서 챗지피티로 설명 들어봄.
> leeje0506 / [DFS/BFS] 다리 만들기 / 골드 3 (실패)

- JIEUN/B7662.java
<a href="https://www.acmicpc.net/problem/7662" rel="nofollow">7662 이중 우선순위 큐</a>
> ex) #405 
앞에서 안되는 문제 풀다가 하려니까 머리가 안 돌아갔다.
풀디가 풀이를 찾아봐버렸다.
우선순위 큐를 2개 쓰는 걸로 풀이를 하는 게 있어서 따라했다.
> leeje0506 / [힙] 이중 우선순위 큐 / 골드 4 (다시풀기)

- minjeong/[BJ]/2146 다리만들기
<a href="https://www.acmicpc.net/problem/2146" rel="nofollow">2146 다리 만들기</a>
아직 인접행렬이 아닌 그래프를 구현하는 것은 어려워 다른 사람 풀이을 참고했다.
> dolmeengii / [DFS/BFS] / 다리만들기 / 골드 3

- minjeong/[BJ]/7662 이중 우선순위 큐
<a href="https://www.acmicpc.net/problem/7662" rel="nofollow">7662 이중 우선순위 큐 </a>
사실 이번주 플젝하느라 시간이 없어서 바로 다른 사람 풀이 참고해서 문제 이해하고 풀이했다. 그런데 이 풀이가 젤 이해하기 쉬웠던 것 같은데 채점까지 시간이 굉장히 오래 걸림. 다시 풀 때는 좀 시간이 덜 걸리는 방식으로 풀이해봐야겠다.
> dolmeengii / [힙] / 이중 우선순위 큐 / 골드4

- minjeong/[BJ]/11559 뿌요뿌요
<a href="https://www.acmicpc.net/problem/11559" rel="nofollow">11559 뿌요뿌요</a>
예전에 빛코마에서 풀이한 적 있던 문제인 것 같기도 한데? 아님 말고... 암튼 이것도 시간 없어서 다른 사람 풀이 봄. 근데 gravity 메서드에서 3중 for문을 사용하는 게 솔직히 보기 좀 그렇다. js 로 다시 풀이할 때 좀 더 효율적인 알고리즘을 적용해서 풀어봐야겠다.
> [시뮬레이션] / 뿌요뿌요 / 골드4

- minjeong/[BJ]/2352 반도체 설계
<a href="https://www.acmicpc.net/problem/2352" rel="nofollow">2352 반도체 설계</a>
이것 또한 마찬가지입니다마. LIS 니가 먼데
> dolmeengii / [dp] 반도체 설계 / 골드2

- minjeong/[BJ]/1781 컵라면
<a href="https://www.acmicpc.net/problem/1781" rel="nofollow">1781 컵라면</a>
이것도 많은 이슈들로 인해 풀이를 먼저 봤는데, 사실 이번주 이분탐색 문제보다 이해하기 더 쉬웠던 것 같다. 물론, 그 풀이한 사람이 잘 풀어서 그럴 수도 ㅎ
프로젝트가 끝나면 1월부터 진행했던 모든 문제를 자바스크립트로 풀이해보는 시간을 가져야겠다.
> dolmeengii / [그리디] 컵라면 / 골드2

- minjeong/[BJ]/2143 두 배열의 합
<a href="https://www.acmicpc.net/problem/2143" rel="nofollow">2143 두 배열의 합</a>
플젝으로 인한 시간없음 + 난이도 이슈로 풀이 보고 이해했습다.
> dolmeengii / [이분탐색] 두 배열의 합 / 골드3

- DONGHEON/[BOJ] 138 두배열의합
<a href="https://www.acmicpc.net/problem/138" rel="nofollow">138 두 배열의 합</a>
#419
A 와 B의 부배열에 해당하는 배열을 모두 생성하여 거기에 대해 이분탐색을 하여 문제를 해결하면 된다. 
이분탐색은 어느 정도 할줄 안다고 생각했는데 약간 꼬여 있으니 머리가 돌아가지 않았다.
풀이 방법을 찾아보고 해결했다 ㅠㅠ
> dongheonchoi / [이분탐색] / 두 배열의 합 / 골드 2

- DONGHEON/[BOJ] 2352 반도체 설계
<a href="https://www.acmicpc.net/problem/2352" rel="nofollow">2352 반도체 설계 </a>
#419
DP를 사용한 문제이다.
lis 에서 최장 인덱스와 그 때 해당하는 원소값을 이용하여 문제를 해결했다
이중 포문을 사용하려다가 터질것 같아서 LIS에 대해 다시 공부할겸 찾아보면서 문제를 풀었다.
알고리즘은 진짜 어떻게 이렇게 풀었지 싶은 재밌는 것들이 많은 것 같다.
> dongheonchoi / [DP] / 반도체 설계 / 골드 2

- JIEUN/B2143.java
<a href="https://www.acmicpc.net/problem/2143" rel="nofollow">2143 두 배열의 합</a>
> ex) #419
> leeje0506 / [이분탐색] 두 배열의 합 / 골드 3

- JIEUN/B1781.java
<a href="https://www.acmicpc.net/problem/1781" rel="nofollow">1781 컵라면</a>
> ex) #419
난이도 올라가서 어려움.
풀다가 막혀서 풀이 찾아서 풀었음. 코테 조졌다;;;
> leeje0506 / [그리디] 컵라면 / 골드 2

- DONGHEON/[BOJ] 1937 욕심쟁이 판다
<a href="https://www.acmicpc.net/problem/1937" rel="nofollow">1937 욕심쟁이 판다</a>
#423 
그냥 다익스트라로 문제를 풀려고 했더니 자꾸 실패를 해서 추가적인 조건을 주었는데도 실패를 하였다.
결국 서칭을 하여 문제를 보니 DP를 추가적으로 사용해야 하는 문제 였다.
위에는 내가 푼 코드 아래는 서칭한 코드를 그대로 가져왔다~
> dongheonchoi / [그래프] 욕심쟁이 판다 / 골드 3

- DONGHEON/[BOJ] 17471 개리맨더링
<a href="https://www.acmicpc.net/problem/17471" rel="nofollow">17471 게리맨더링</a>
#423
두 지역구를 나눈 다음 해당 지역구가 모두 연결되어 있는지 확인하고 만약 그렇다면 두 지역구의 인구의 차이를 계산하면된다.
1년 전에 풀어봤던 문제인데 다시 보니 가물가물...
> dongheonchoi / [완전탐색] 개리맨더링 / 골드 3

- JIEUN/B17471.java
<a href="https://www.acmicpc.net/problem/17471" rel="nofollow">17471 게리멘더링</a>
> #423
가능한 모든 조합을 확인하고, 각 그룹이 연결되어있는지 BFS로 본다.
> leeje0506 / [완전탐색] 게리맨더링 / 골드 3

- JIEUN/B1937.java
<a href="https://www.acmicpc.net/problem/1937" rel="nofollow">1937 욕심쟁이 판다</a>
> #423 
DFS로 각 칸에서 갈 수 있는 최대 경로 구함.
중복 방지하고, 모든 칸을 시작점으로 시도해서 최댓값을 갱신함.
> leeje0506 / [그래프] 욕심쟁이 판다 / 골드 3

- JIEUN/B19835.java
<a href="https://www.acmicpc.net/problem/19835" rel="nofollow">19835 면접보는 승범이네</a>
> #423 
도시에서 면접장까지 거리를 생각하는 게 어려웠다.
각 도시마다 다익스트라 돌려야 하나? 라고 생각했는데, 출발을 면접장으로 두고 역방향 그래프를 그리면 그나마 쉬웠다. 도달 가능한 최소 거리가 중요한 거라 방향은 상관없다는 부분을 놓쳤던 듯...
그래프 역방향이나, 시작점이 여러 개인 다익스트라 문제 같아서 어려웠다. 처음에 방향 막혔을 때부터 찾아봐서 코드는 완성했는데, 다시 생각을 좀 해봐야할 문제라고 생각.
> leeje0506 / [다익스트라] 면접보는 승범이네 / 골드 2

- minjeong/[PG]/42889 실패율
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/42889" rel="nofollow">42889 실패율</a>
스테이지 별로 도전자 수와 실패자 수를 각각 구한다. 
각 스테이지마다 실패율을 계산해주는데, 도전한 사람이 없으면 실패율은 0이 되므로 조건문을 걸어준다.
코드를 돌려봤더니 자꾸 0이 섞여 들어가서 도대체 어디가 문제지 하고 한참 찾았는데 알고보니 for문으로 스테이지를 0부터 순회했던 것...
우하하 고쳤더니 잘됨
메서드 쓰는 걸 좀 더 익혀야겠다.
> dolmeengii / [PGS] 실패율 / level 1

- minjeong/[PG]/42840 모의고사
<a href="https://school.programmers.co.kr/learn/courses/30/lessons/42840" rel="nofollow">42840 모의고사</a>
패턴과 정답표를 비교하여 점수를 추가해주면 된다.
동점자 발생시 오름차순으로 정렬도 해야한다!
entries() 를 사용하면 배열/객체의 내용을 index-value 혹은 key-value 쌍으로 묶을 수 있다.
arr.entries() 처럼 사용하고자 하는 배열이나 객체에서 메서드처럼 사용하면 된다. 
반환되는 값은 iterator 이면 for-of 문법과 함께 사용가능하다. 
``` javascript
const arr = ['a', 'b', 'c'];
for (const [index, value] of arr.entries()) {
console.log(index, value);
}
```
자스로 알고리즘을 풀 때에 이런 저런 메서드를 잘 사용하는 게 중요하군...
> dolmeengii / [PGS] 모의고사 / level 1

- DONGHEON/[BOJ] 1461 도서관
<a href="https://www.acmicpc.net/problem/1461" rel="nofollow">1461 도서관</a>
#439
양수와 음수에 대한 수의 처리를 잘해주면 되는 문제이다.
수를 묶는 방법은 절대 값이 큰 수 부터 차례대로 묶어 나가야 한다.
우선 순위 큐를 음수와 양수 두번에 걸쳐서 사용하면 된다.
너무 오래 쉬었더니 감이 많이 죽었다.
> donheonchoi / [그리드] 도서관 / 골드 4
